In [1]:
!pip install atproto pandas networkx tqdm pyarrow

Requirement already satisfied: atproto in /opt/anaconda3/lib/python3.13/site-packages (0.0.69)
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.3.2)
Requirement already satisfied: networkx in /opt/anaconda3/lib/python3.13/site-packages (3.4.2)
Requirement already satisfied: tqdm in /opt/anaconda3/lib/python3.13/site-packages (4.67.1)
Requirement already satisfied: pyarrow in /opt/anaconda3/lib/python3.13/site-packages (19.0.0)
Requirement already satisfied: click<9,>=8.1.3 in /opt/anaconda3/lib/python3.13/site-packages (from atproto) (8.1.8)
Requirement already satisfied: cryptography<47,>=41.0.7 in /opt/anaconda3/lib/python3.13/site-packages (from atproto) (44.0.1)
Requirement already satisfied: dnspython<3,>=2.4.0 in /opt/anaconda3/lib/python3.13/site-packages (from atproto) (2.8.0)
Requirement already satisfied: httpx<0.29.0,>=0.25.0 in /opt/anaconda3/lib/python3.13/site-packages (from atproto) (0.28.1)
Requirement already satisfied: libipld<4,>=3.0.1 in /opt/anaconda3/lib/python3.13/site-packages (from atproto) (3.4.1)
Requirement already satisfied: pydantic<3,>=2.7 in /opt/anaconda3/lib/python3.13/site-packages (from atproto) (2.10.3)
Requirement already satisfied: typing-extensions<5,>=4.8.0 in /opt/anaconda3/lib/python3.13/site-packages (from atproto) (4.12.2)
Requirement already satisfied: websockets<16,>=15 in /opt/anaconda3/lib/python3.13/site-packages (from atproto) (15.0.1)
Requirement already satisfied: cffi>=1.12 in /opt/anaconda3/lib/python3.13/site-packages (from cryptography<47,>=41.0.7->atproto) (1.17.1)
Requirement already satisfied: anyio in /opt/anaconda3/lib/python3.13/site-packages (from httpx<0.29.0,>=0.25.0->atproto) (4.7.0)
Requirement already satisfied: certifi in /opt/anaconda3/lib/python3.13/site-packages (from httpx<0.29.0,>=0.25.0->atproto) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /opt/anaconda3/lib/python3.13/site-packages (from httpx<0.29.0,>=0.25.0->atproto) (1.0.9)
Requirement already satisfied: idna in /opt/anaconda3/lib/python3.13/site-packages (from httpx<0.29.0,>=0.25.0->atproto) (3.7)
Requirement already satisfied: h11>=0.16 in /opt/anaconda3/lib/python3.13/site-packages (from httpcore==1.*->httpx<0.29.0,>=0.25.0->atproto) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic<3,>=2.7->atproto) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in /opt/anaconda3/lib/python3.13/site-packages (from pydantic<3,>=2.7->atproto) (2.27.1)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.13/site-packages (from cffi>=1.12->cryptography<47,>=41.0.7->atproto) (2.21)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: sniffio>=1.1 in /opt/anaconda3/lib/python3.13/site-packages (from anyio->httpx<0.29.0,>=0.25.0->atproto) (1.3.0)

In [2]:
!pip install matplotlib

Requirement already satisfied: matplotlib in /opt/anaconda3/lib/python3.13/site-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (2.1.3)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

In [3]:
%pip install atproto

Requirement already satisfied: atproto in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (0.0.69)
Requirement already satisfied: click<9,>=8.1.3 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from atproto) (8.4.2)
Requirement already satisfied: cryptography<47,>=41.0.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from atproto) (46.0.7)
Requirement already satisfied: dnspython<3,>=2.4.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from atproto) (2.8.0)
Requirement already satisfied: httpx<0.29.0,>=0.25.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from atproto) (0.28.1)
Requirement already satisfied: libipld<4,>=3.0.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from atproto) (3.4.1)
Requirement already satisfied: pydantic<3,>=2.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from atproto) (2.13.4)
Requirement already satisfied: typing-extensions<5,>=4.8.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from atproto) (4.15.0)
Requirement already satisfied: websockets<16,>=15 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from atproto) (15.0.1)
Requirement already satisfied: cffi>=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from cryptography<47,>=41.0.7->atproto) (2.0.0)
Requirement already satisfied: anyio in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from httpx<0.29.0,>=0.25.0->atproto) (4.14.1)
Requirement already satisfied: certifi in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from httpx<0.29.0,>=0.25.0->atproto) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from httpx<0.29.0,>=0.25.0->atproto) (1.0.9)
Requirement already satisfied: idna in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from httpx<0.29.0,>=0.25.0->atproto) (3.18)
Requirement already satisfied: h11>=0.16 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from httpcore==1.*->httpx<0.29.0,>=0.25.0->atproto) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pydantic<3,>=2.7->atproto) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pydantic<3,>=2.7->atproto) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pydantic<3,>=2.7->atproto) (0.4.2)
Requirement already satisfied: pycparser in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from cffi>=2.0.0->cryptography<47,>=41.0.7->atproto) (3.0)

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [4]:
from atproto import Client

BSKY_HANDLE = "flena.bsky.social"
BSKY_APP_PASSWORD = "25s3-doqo-rngr-lnma"

client = Client()
client.login(BSKY_HANDLE, BSKY_APP_PASSWORD)

ProfileViewDetailed(did='did:plc:zsdps3mbxwbypep6e33hd5p5', handle='flena.bsky.social', associated=ProfileAssociated(activity_subscription=ProfileAssociatedActivitySubscription(allow_subscriptions='followers', py_type='app.bsky.actor.defs#profileAssociatedActivitySubscription'), chat=None, feedgens=0, germ=None, labeler=False, lists=0, starter_packs=0, py_type='app.bsky.actor.defs#profileAssociated'), avatar='https://cdn.bsky.app/img/avatar/plain/did:plc:zsdps3mbxwbypep6e33hd5p5/bafkreiacmnedzm5gc6w2254chanxadojhkelmnahsokjzvpu35v3bxwgka', banner=None, created_at='2026-06-30T12:53:06.623Z', debug=None, description=None, display_name='', followers_count=0, follows_count=1, indexed_at='2026-06-30T12:53:56.020Z', joined_via_starter_pack=None, labels=[], pinned_post=None, posts_count=0, pronouns=None, status=None, verification=None, viewer=ViewerState(activity_subscription=None, blocked_by=False, blocking=None, blocking_by_list=None, followed_by=None, following=None, known_followers=None, muted=False, muted_by_list=None, py_type='app.bsky.actor.defs#viewerState'), website=None, py_type='app.bsky.actor.defs#profileViewDetailed')

In [6]:
# ============================================================
# SERIOUS TICKER WHITELIST FROM NASDAQ TRADER SYMBOL DIRECTORY
# Compatible with Jupyter/VS Code even if current folder is read-only
# ============================================================

import pandas as pd
import re
import os
import tempfile
from pathlib import Path
from io import StringIO

# If requests/certifi are missing, install them first in a separate cell:
# %pip install requests certifi

import requests
import certifi


# ------------------------------------------------------------
# 1. Create a writable output directory
# ------------------------------------------------------------

def get_writable_output_dir():
    candidate_dirs = [
        Path.cwd() / "outputs",
        Path.home() / "bluesky_sna_outputs",
        Path(tempfile.gettempdir()) / "bluesky_sna_outputs",
    ]

    for directory in candidate_dirs:
        try:
            directory.mkdir(parents=True, exist_ok=True)
            test_file = directory / ".write_test"
            test_file.write_text("test")
            test_file.unlink()
            return directory
        except Exception:
            continue

    raise OSError("No writable output directory found.")

OUTPUT_DIR = get_writable_output_dir()

print("Output directory:", OUTPUT_DIR)
print("Writable:", os.access(OUTPUT_DIR, os.W_OK))


# ------------------------------------------------------------
# 2. Nasdaq Trader URLs
# ------------------------------------------------------------

NASDAQ_LISTED_URL = "https://www.nasdaqtrader.com/dynamic/symdir/nasdaqlisted.txt"
OTHER_LISTED_URL = "https://www.nasdaqtrader.com/dynamic/symdir/otherlisted.txt"


# ------------------------------------------------------------
# 3. Robust downloader
# ------------------------------------------------------------

def download_text_file(url):
    """
    Downloads a public text file using requests + certifi.
    This avoids pandas/urllib SSL problems on some Mac/Python installs.
    """
    headers = {
        "User-Agent": "Mozilla/5.0 academic-research-project"
    }

    response = requests.get(
        url,
        headers=headers,
        timeout=30,
        verify=certifi.where()
    )

    response.raise_for_status()
    return response.text


def read_pipe_separated_url(url):
    text = download_text_file(url)

    # Remove empty lines
    lines = [line for line in text.splitlines() if line.strip()]

    # Remove final metadata line if present
    lines = [
        line for line in lines
        if not line.startswith("File Creation Time")
    ]

    cleaned_text = "\n".join(lines)

    return pd.read_csv(StringIO(cleaned_text), sep="|")


# ------------------------------------------------------------
# 4. Load Nasdaq-listed securities
# ------------------------------------------------------------

def load_nasdaq_listed():
    df = read_pipe_separated_url(NASDAQ_LISTED_URL)

    df = df[df["Symbol"].notna()].copy()

    df = df.rename(columns={
        "Symbol": "ticker",
        "Security Name": "security_name",
        "Market Category": "market_category",
        "Test Issue": "test_issue",
        "ETF": "etf"
    })

    df["source_file"] = "nasdaqlisted"
    df["exchange_group"] = "NASDAQ"

    return df[[
        "ticker",
        "security_name",
        "market_category",
        "test_issue",
        "etf",
        "source_file",
        "exchange_group"
    ]]


# ------------------------------------------------------------
# 5. Load other exchange-listed securities
# ------------------------------------------------------------

def load_other_listed():
    df = read_pipe_separated_url(OTHER_LISTED_URL)

    df = df[df["ACT Symbol"].notna()].copy()

    df = df.rename(columns={
        "ACT Symbol": "ticker",
        "Security Name": "security_name",
        "Exchange": "exchange_group",
        "Test Issue": "test_issue",
        "ETF": "etf"
    })

    df["market_category"] = None
    df["source_file"] = "otherlisted"

    return df[[
        "ticker",
        "security_name",
        "market_category",
        "test_issue",
        "etf",
        "source_file",
        "exchange_group"
    ]]


# ------------------------------------------------------------
# 6. Build raw ticker universe
# ------------------------------------------------------------

raw_nasdaq = load_nasdaq_listed()
raw_other = load_other_listed()

tickers_raw = pd.concat([raw_nasdaq, raw_other], ignore_index=True)

tickers_raw["ticker"] = tickers_raw["ticker"].astype(str).str.upper().str.strip()
tickers_raw["security_name"] = tickers_raw["security_name"].astype(str)

tickers_raw = tickers_raw.drop_duplicates(subset=["ticker"])
tickers_raw = tickers_raw.sort_values("ticker").reset_index(drop=True)

print("Raw securities:", len(tickers_raw))

display(tickers_raw.head(20))


# ------------------------------------------------------------
# 7. Save raw ticker universe
# ------------------------------------------------------------

raw_path = OUTPUT_DIR / "us_listed_securities_raw.csv"
tickers_raw.to_csv(raw_path, index=False)

print("Saved raw securities to:", raw_path)

Output directory: /Users/bucco/Downloads/outputs
Writable: True
Raw securities: 12931

,ticker,security_name,market_category,test_issue,etf,source_file,exchange_group
0,A,"Agilent Technologies, Inc. Common Stock",None,N,N,otherlisted,N
1,AA,Alcoa Corporation Common Stock,None,N,N,otherlisted,N
2,AAA,Alternative Access First Priority CLO Bond ETF,None,N,Y,otherlisted,P
3,AAAA,Amplius Aggressive Asset Allocation ETF,None,N,Y,otherlisted,Z
4,AAAC,Columbia AAA CLO ETF,None,N,Y,otherlisted,P
5,AAAD,PGIM AAA CLO Aggregate Duration ETF,None,N,Y,otherlisted,P
6,AAAP,Pacer Barings CLO Market Flex ETF,G,N,Y,nasdaqlisted,NASDAQ
7,AAAU,Goldman Sachs Physical Gold ETF Shares,None,N,Y,otherlisted,Z
8,AAC.U,"Ares Acquisition Corporation III Units, each c...",None,N,N,otherlisted,N
9,AACB,Artius II Acquisition Inc. - Class A Ordinary ...,G,N,N,nasdaqlisted,NASDAQ
10,AACBR,Artius II Acquisition Inc. - Rights,G,N,N,nasdaqlisted,NASDAQ
11,AACBU,Artius II Acquisition Inc. - Units,G,N,N,nasdaqlisted,NASDAQ
12,AACG,ATA Creativity Global - American Depositary Sh...,S,N,N,nasdaqlisted,NASDAQ
13,AACI,Armada Acquisition Corp. III - Class A Ordinar...,G,N,N,nasdaqlisted,NASDAQ
14,AACIU,Armada Acquisition Corp. III - Units,G,N,N,nasdaqlisted,NASDAQ
15,AACIW,Armada Acquisition Corp. III - Warrant,G,N,N,nasdaqlisted,NASDAQ
16,AACO,Abony Acquisition Corp. I - Class A Ordinary S...,G,N,N,nasdaqlisted,NASDAQ
17,AACOU,Abony Acquisition Corp. I - Units,G,N,N,nasdaqlisted,NASDAQ
18,AACOW,Abony Acquisition Corp. I - Warrants,G,N,N,nasdaqlisted,NASDAQ
19,AACP,Apogee Acquisition Corp - Class A Ordinary Shares,G,N,N,nasdaqlisted,NASDAQ

Saved raw securities to: /Users/bucco/Downloads/outputs/us_listed_securities_raw.csv

In [7]:
# ============================================================
# BUILD CLEAN WHITELISTS:
# 1. stock_like_tickers: stricter equity-like universe
# 2. financial_symbols: broad listed financial instruments universe
# ============================================================

import re

# ------------------------------------------------------------
# 1. Basic cleaning
# ------------------------------------------------------------

tickers_clean = tickers_raw.copy()

tickers_clean["ticker"] = (
    tickers_clean["ticker"]
    .astype(str)
    .str.upper()
    .str.strip()
)

tickers_clean["security_name"] = (
    tickers_clean["security_name"]
    .astype(str)
    .str.strip()
)

tickers_clean["test_issue"] = (
    tickers_clean["test_issue"]
    .astype(str)
    .str.upper()
    .str.strip()
)

tickers_clean["etf"] = (
    tickers_clean["etf"]
    .astype(str)
    .str.upper()
    .str.strip()
)

# Remove test issues
tickers_clean = tickers_clean[tickers_clean["test_issue"] == "N"].copy()

# Keep only ticker formats that can realistically appear as Bluesky cashtags
# Examples: AAPL, BRK.B, BF.A, RDS-A
tickers_clean = tickers_clean[
    tickers_clean["ticker"].str.match(r"^[A-Z0-9][A-Z0-9\.\-]{0,9}$", na=False)
].copy()

tickers_clean = tickers_clean.drop_duplicates(subset=["ticker"])
tickers_clean = tickers_clean.sort_values("ticker").reset_index(drop=True)

print("Clean listed securities:", len(tickers_clean))


# ------------------------------------------------------------
# 2. Broad whitelist: listed financial symbols
# ------------------------------------------------------------
# This is the recommended whitelist for your Bluesky project
# if the target is a large ticker/asset co-mention network.

financial_symbols_df = tickers_clean.copy()

financial_symbols = sorted(financial_symbols_df["ticker"].unique())

financial_symbols_path = OUTPUT_DIR / "us_listed_financial_symbols_whitelist.csv"
financial_symbols_txt_path = OUTPUT_DIR / "us_listed_financial_symbols.txt"

financial_symbols_df.to_csv(financial_symbols_path, index=False)

with open(financial_symbols_txt_path, "w") as f:
    for ticker in financial_symbols:
        f.write(ticker + "\n")

print("Broad financial symbols:", len(financial_symbols))
print("Saved:", financial_symbols_path)
print("Saved:", financial_symbols_txt_path)


# ------------------------------------------------------------
# 3. Stricter stock-like whitelist
# ------------------------------------------------------------
# This tries to remove ETFs, funds, warrants, units, rights,
# preferred shares, notes, bonds, and other non-common-equity instruments.
# It is useful for reporting a cleaner stock-only universe.

EXCLUDE_NAME_PATTERNS = [
    r"\bETF\b",
    r"\bETFS\b",
    r"\bETN\b",
    r"\bETNS\b",
    r"\bFUND\b",
    r"\bTRUST\b",
    r"\bINDEX\b",
    r"\bPORTFOLIO\b",
    r"\bINCOME\b",
    r"\bWARRANT\b",
    r"\bWARRANTS\b",
    r"\bRIGHT\b",
    r"\bRIGHTS\b",
    r"\bUNIT\b",
    r"\bUNITS\b",
    r"\bPREFERRED\b",
    r"\bPREFERENCE\b",
    r"\bPREF\b",
    r"\bDEPOSITARY\b",
    r"\bDEPOSITORY\b",
    r"\bNOTE\b",
    r"\bNOTES\b",
    r"\bBOND\b",
    r"\bBONDS\b",
    r"\bDEBENTURE\b",
    r"\bDEBENTURES\b",
    r"\bSERIES\b",
    r"\bREIT\b",
    r"\bSPAC\b",
    r"\bACQUISITION CORP.*UNIT\b",
    r"\bCLOSED END\b",
    r"\bCLOSED-END\b",
    r"\bBENEFICIAL INTEREST\b",
    r"\bCONVERTIBLE\b",
    r"\bCALLABLE\b",
    r"\bFLOATING RATE\b",
    r"\bSENIOR\b",
    r"\bSUBORDINATED\b",
]

EXCLUDE_TICKER_PATTERNS = [
    r"\.W$",
    r"\.WS$",
    r"\.WT$",
    r"\.U$",
    r"\.R$",
    r"\.RT$",
    r"\.P$",
    r"\.PR",
    r"\.A$",
    r"\.B$",
    r"\.C$",
    r"\.D$",
    r"\.E$",
    r"\.F$",
    r"\.G$",
    r"\.H$",
    r"\.I$",
    r"\.J$",
    r"\.K$",
    r"\.L$",
    r"\.M$",
    r"\.N$",
    r"\.O$",
    r"\.P$",
    r"\.Q$",
    r"\.R$",
    r"\.S$",
    r"\.T$",
    r"\.U$",
    r"\.V$",
    r"\.W$",
    r"\.X$",
    r"\.Y$",
    r"\.Z$",
]

def is_excluded_stock_like(row):
    name = str(row["security_name"]).upper()
    ticker = str(row["ticker"]).upper()

    # remove ETFs directly from Nasdaq field
    if str(row["etf"]).upper() == "Y":
        return True

    for pattern in EXCLUDE_NAME_PATTERNS:
        if re.search(pattern, name, flags=re.IGNORECASE):
            return True

    for pattern in EXCLUDE_TICKER_PATTERNS:
        if re.search(pattern, ticker, flags=re.IGNORECASE):
            return True

    return False

stock_like_df = tickers_clean[
    ~tickers_clean.apply(is_excluded_stock_like, axis=1)
].copy()

stock_like_df = stock_like_df.sort_values("ticker").reset_index(drop=True)

stock_like_tickers = sorted(stock_like_df["ticker"].unique())

stock_like_path = OUTPUT_DIR / "us_stock_like_ticker_whitelist.csv"
stock_like_txt_path = OUTPUT_DIR / "us_stock_like_tickers.txt"

stock_like_df.to_csv(stock_like_path, index=False)

with open(stock_like_txt_path, "w") as f:
    for ticker in stock_like_tickers:
        f.write(ticker + "\n")

print("Stock-like tickers:", len(stock_like_tickers))
print("Saved:", stock_like_path)
print("Saved:", stock_like_txt_path)


# ------------------------------------------------------------
# 4. Display examples
# ------------------------------------------------------------

print("\nExamples from broad financial symbols:")
display(financial_symbols_df.head(20))

print("\nExamples from stricter stock-like symbols:")
display(stock_like_df.head(20))

Clean listed securities: 12511
Broad financial symbols: 12511
Saved: /Users/bucco/Downloads/outputs/us_listed_financial_symbols_whitelist.csv
Saved: /Users/bucco/Downloads/outputs/us_listed_financial_symbols.txt
Stock-like tickers: 5085
Saved: /Users/bucco/Downloads/outputs/us_stock_like_ticker_whitelist.csv
Saved: /Users/bucco/Downloads/outputs/us_stock_like_tickers.txt

Examples from broad financial symbols:

,ticker,security_name,market_category,test_issue,etf,source_file,exchange_group
0,A,"Agilent Technologies, Inc. Common Stock",None,N,N,otherlisted,N
1,AA,Alcoa Corporation Common Stock,None,N,N,otherlisted,N
2,AAA,Alternative Access First Priority CLO Bond ETF,None,N,Y,otherlisted,P
3,AAAA,Amplius Aggressive Asset Allocation ETF,None,N,Y,otherlisted,Z
4,AAAC,Columbia AAA CLO ETF,None,N,Y,otherlisted,P
5,AAAD,PGIM AAA CLO Aggregate Duration ETF,None,N,Y,otherlisted,P
6,AAAP,Pacer Barings CLO Market Flex ETF,G,N,Y,nasdaqlisted,NASDAQ
7,AAAU,Goldman Sachs Physical Gold ETF Shares,None,N,Y,otherlisted,Z
8,AAC.U,"Ares Acquisition Corporation III Units, each c...",None,N,N,otherlisted,N
9,AACB,Artius II Acquisition Inc. - Class A Ordinary ...,G,N,N,nasdaqlisted,NASDAQ
10,AACBR,Artius II Acquisition Inc. - Rights,G,N,N,nasdaqlisted,NASDAQ
11,AACBU,Artius II Acquisition Inc. - Units,G,N,N,nasdaqlisted,NASDAQ
12,AACG,ATA Creativity Global - American Depositary Sh...,S,N,N,nasdaqlisted,NASDAQ
13,AACI,Armada Acquisition Corp. III - Class A Ordinar...,G,N,N,nasdaqlisted,NASDAQ
14,AACIU,Armada Acquisition Corp. III - Units,G,N,N,nasdaqlisted,NASDAQ
15,AACIW,Armada Acquisition Corp. III - Warrant,G,N,N,nasdaqlisted,NASDAQ
16,AACO,Abony Acquisition Corp. I - Class A Ordinary S...,G,N,N,nasdaqlisted,NASDAQ
17,AACOU,Abony Acquisition Corp. I - Units,G,N,N,nasdaqlisted,NASDAQ
18,AACOW,Abony Acquisition Corp. I - Warrants,G,N,N,nasdaqlisted,NASDAQ
19,AACP,Apogee Acquisition Corp - Class A Ordinary Shares,G,N,N,nasdaqlisted,NASDAQ

Examples from stricter stock-like symbols:

,ticker,security_name,market_category,test_issue,etf,source_file,exchange_group
0,A,"Agilent Technologies, Inc. Common Stock",None,N,N,otherlisted,N
1,AA,Alcoa Corporation Common Stock,None,N,N,otherlisted,N
2,AACB,Artius II Acquisition Inc. - Class A Ordinary ...,G,N,N,nasdaqlisted,NASDAQ
3,AACI,Armada Acquisition Corp. III - Class A Ordinar...,G,N,N,nasdaqlisted,NASDAQ
4,AACO,Abony Acquisition Corp. I - Class A Ordinary S...,G,N,N,nasdaqlisted,NASDAQ
5,AACP,Apogee Acquisition Corp - Class A Ordinary Shares,G,N,N,nasdaqlisted,NASDAQ
6,AADX,"Applied Aerospace & Defense, Inc. Common Stock",None,N,N,otherlisted,N
7,AAL,"American Airlines Group, Inc. - Common Stock",Q,N,N,nasdaqlisted,NASDAQ
8,AAME,Atlantic American Corporation - Common Stock,G,N,N,nasdaqlisted,NASDAQ
9,AAMI,Acadian Asset Management Inc. Common Stock,None,N,N,otherlisted,N
10,AAOI,"Applied Optoelectronics, Inc. - Common Stock",G,N,N,nasdaqlisted,NASDAQ
11,AAON,"AAON, Inc. - Common Stock",Q,N,N,nasdaqlisted,NASDAQ
12,AAP,Advance Auto Parts Inc.,None,N,N,otherlisted,N
13,AAPL,Apple Inc. - Common Stock,Q,N,N,nasdaqlisted,NASDAQ
14,AARD,"Aardvark Therapeutics, Inc. - Common Stock",Q,N,N,nasdaqlisted,NASDAQ
15,AAUC,Allied Gold Corporation Common Shares,None,N,N,otherlisted,N
16,ABAT,American Battery Technology Company - Common S...,S,N,N,nasdaqlisted,NASDAQ
17,ABBV,AbbVie Inc. Common Stock,None,N,N,otherlisted,N
18,ABCB,Ameris Bancorp Common Stock,None,N,N,otherlisted,N
19,ABCL,AbCellera Biologics Inc. - Common Shares,Q,N,N,nasdaqlisted,NASDAQ

In [9]:
# ============================================================
# BLUESKY LOGIN
# ============================================================

from atproto import Client

BSKY_HANDLE = "flena.bsky.social"
BSKY_APP_PASSWORD = "tezo-jnci-pdfb-3aia"

client = Client()
profile = client.login(BSKY_HANDLE, BSKY_APP_PASSWORD)

print("Logged in as:", profile.handle)

Logged in as: flena.bsky.social

In [10]:
# ============================================================
# PREPARE VALID TICKER SET FOR BLUESKY EXTRACTION
# ============================================================

VALID_TICKERS = set(financial_symbols)

print("Valid tickers in whitelist:", len(VALID_TICKERS))

# Some tickers contain dots or dashes. Bluesky users may write them differently.
# Example: BRK.B may appear as $BRK.B, $BRK-B, or sometimes $BRKB.
# We create a simple alias map to improve matching.

TICKER_ALIAS_TO_CANONICAL = {}

for ticker in VALID_TICKERS:
    canonical = ticker.upper().strip()
    TICKER_ALIAS_TO_CANONICAL[canonical] = canonical
    
    # Dot/dash variants
    if "." in canonical:
        TICKER_ALIAS_TO_CANONICAL[canonical.replace(".", "-")] = canonical
        TICKER_ALIAS_TO_CANONICAL[canonical.replace(".", "")] = canonical
    
    if "-" in canonical:
        TICKER_ALIAS_TO_CANONICAL[canonical.replace("-", ".")] = canonical
        TICKER_ALIAS_TO_CANONICAL[canonical.replace("-", "")] = canonical

print("Ticker aliases:", len(TICKER_ALIAS_TO_CANONICAL))

Valid tickers in whitelist: 12511
Ticker aliases: 12824

In [11]:
# ============================================================
# EXTRACT VALID CASHTAG TICKERS FROM POST TEXT
# ============================================================

import re

CASHTAG_REGEX = re.compile(
    r"(?<![A-Za-z0-9])\$([A-Za-z0-9][A-Za-z0-9\.\-]{0,9})(?![A-Za-z0-9])"
)

def extract_valid_cashtag_tickers(text):
    """
    Extracts valid financial tickers from a Bluesky post.
    Only $CASHTAG-style mentions are accepted.
    The extracted symbols are validated against the Nasdaq Trader whitelist.
    """
    if not isinstance(text, str):
        return []

    raw_matches = CASHTAG_REGEX.findall(text)

    valid = set()

    for raw in raw_matches:
        candidate = raw.upper().strip()
        
        if candidate in TICKER_ALIAS_TO_CANONICAL:
            valid.add(TICKER_ALIAS_TO_CANONICAL[candidate])

    return sorted(valid)


# Quick test
test_text = "Watching $AAPL $MSFT $NVDA and $BRK.B today. Also random $LOL."
print(extract_valid_cashtag_tickers(test_text))

['AAPL', 'BRK.B', 'MSFT', 'NVDA']

In [12]:
# ============================================================
# FINANCE-RELATED SEARCH QUERIES
# ============================================================

QUERIES = [
    # General finance
    "stocks",
    "stock market",
    "markets",
    "trading",
    "investing",
    "investors",
    "earnings",
    "earnings season",
    "options",
    "options trading",
    "portfolio",
    "dividends",
    "short squeeze",
    "market rally",
    "market crash",
    "bull market",
    "bear market",

    # Sectors
    "AI stocks",
    "tech stocks",
    "semiconductor stocks",
    "bank stocks",
    "energy stocks",
    "oil stocks",
    "biotech stocks",
    "pharma stocks",
    "EV stocks",
    "defense stocks",

    # ETFs / indices
    "$SPY",
    "$QQQ",
    "$IWM",
    "$DIA",
    "$VTI",
    "$VOO",
    "$TLT",
    "$GLD",
    "$SLV",

    # Mega-cap / frequent finance cashtags
    "$AAPL",
    "$MSFT",
    "$NVDA",
    "$TSLA",
    "$META",
    "$AMZN",
    "$GOOGL",
    "$GOOG",
    "$AMD",
    "$INTC",
    "$NFLX",
    "$AVGO",
    "$ORCL",
    "$PLTR",
    "$SMCI",
    "$COIN",
    "$MSTR",

    # Crypto-related listed equities / common symbols
    "bitcoin stocks",
    "crypto stocks",
    "$BTC",
    "$ETH",
    "$MARA",
    "$RIOT",
    "$CLSK",
    "$HOOD",
]

In [13]:
# ============================================================
# COLLECT POSTS FROM BLUESKY SEARCH
# ============================================================

import time
import pandas as pd
from tqdm import tqdm

def search_posts_for_query(client, query, max_pages=5, limit=100, sleep_seconds=0.5):
    """
    Collects Bluesky posts for a single query using app.bsky.feed.searchPosts.
    """
    posts = []
    cursor = None

    for page in range(max_pages):
        params = {
            "q": query,
            "limit": limit,
        }

        if cursor:
            params["cursor"] = cursor

        try:
            response = client.app.bsky.feed.search_posts(params)
        except Exception as e:
            print(f"Error for query={query}, page={page + 1}: {e}")
            break

        response_posts = getattr(response, "posts", [])

        if not response_posts:
            break

        for post in response_posts:
            record = getattr(post, "record", None)
            text = getattr(record, "text", "") if record else ""
            created_at = getattr(record, "created_at", None) if record else None

            posts.append({
                "query": query,
                "uri": getattr(post, "uri", None),
                "cid": getattr(post, "cid", None),
                "author_handle": getattr(post.author, "handle", None),
                "author_did": getattr(post.author, "did", None),
                "created_at": created_at,
                "text": text,
                "like_count": getattr(post, "like_count", 0),
                "reply_count": getattr(post, "reply_count", 0),
                "repost_count": getattr(post, "repost_count", 0),
                "quote_count": getattr(post, "quote_count", 0),
            })

        cursor = getattr(response, "cursor", None)

        if not cursor:
            break

        time.sleep(sleep_seconds)

    return posts


all_posts = []

for query in tqdm(QUERIES):
    query_posts = search_posts_for_query(
        client=client,
        query=query,
        max_pages=5,
        limit=100,
        sleep_seconds=0.5
    )
    all_posts.extend(query_posts)
    time.sleep(1)

posts_df = pd.DataFrame(all_posts)

if len(posts_df) > 0:
    posts_df = posts_df.drop_duplicates(subset=["uri"]).reset_index(drop=True)

print("Collected posts:", len(posts_df))

display(posts_df.head(10))

  0%|          | 0/61 [00:00<?, ?it/s]

Error for query=stocks, page=4:

 10%|▉         | 6/61 [00:52<07:26,  8.13s/it]

Error for query=earnings, page=3:

 25%|██▍       | 15/61 [02:07<05:40,  7.40s/it]

Error for query=bull market, page=2:

 38%|███▊      | 23/61 [03:05<04:15,  6.72s/it]

Error for query=biotech stocks, page=1:

 39%|███▉      | 24/61 [03:11<04:00,  6.51s/it]

Error for query=pharma stocks, page=1:

 51%|█████     | 31/61 [03:58<03:32,  7.09s/it]

Error for query=$VTI, page=4:

 80%|████████  | 49/61 [06:01<01:17,  6.48s/it]

Error for query=$PLTR, page=2:

 93%|█████████▎| 57/61 [07:02<00:34,  8.69s/it]

Error for query=$MARA, page=5:

100%|██████████| 61/61 [07:44<00:00,  7.62s/it]

Collected posts: 24766

,query,uri,cid,author_handle,author_did,created_at,text,like_count,reply_count,repost_count,quote_count
0,stocks,at://did:plc:ilqsyryppoq2vgipjp3fnxiw/app.bsky...,bafyreigmwt4idfs3nwiwli7pqe2jsanec42tlounnfnro...,secwatch.bsky.social,did:plc:ilqsyryppoq2vgipjp3fnxiw,2026-06-30T13:07:23.556665Z,🚨 JUST IN: $HCWB\nHCW Biologics regains Nasdaq...,0,0,0,0
1,stocks,at://did:plc:ilqsyryppoq2vgipjp3fnxiw/app.bsky...,bafyreifuu6gsuuxl23yacycktrrgs7m5ban2q7b7cnnot...,secwatch.bsky.social,did:plc:ilqsyryppoq2vgipjp3fnxiw,2026-06-30T13:07:22.402435Z,🚨 JUST IN: $QXO\nQXO reports 99.5%+ tender of ...,0,0,0,0
2,stocks,at://did:plc:gtw57nuw4wt2tqs322knhgim/app.bsky...,bafyreib3paf5vp3ojkgoauwnd73xw2juzqr5mmrdtqvk4...,capitalwisdom.bsky.social,did:plc:gtw57nuw4wt2tqs322knhgim,2026-06-30T13:07:15.980401+00:00,"📈 Capital Wisdom Top Picks — Jun 30, 2026\n\n$...",0,0,0,0
3,stocks,at://did:plc:xhrtfphu4gzqrztkpb3a63qf/app.bsky...,bafyreif355gfx3gqcp6pbyzngywx422y7esnflrfxg6ma...,babygoldie.bsky.social,did:plc:xhrtfphu4gzqrztkpb3a63qf,2026-06-30T13:06:15.262304+00:00,"[3/4] in the future. After verification, the c...",0,1,0,0
4,stocks,at://did:plc:xhrtfphu4gzqrztkpb3a63qf/app.bsky...,bafyreic6sbrvrz47nmpzdktcj36ccjnsdkogpagewbwxk...,babygoldie.bsky.social,did:plc:xhrtfphu4gzqrztkpb3a63qf,2026-06-30T13:05:57.076841+00:00,[3/4] interest rates appear to be overdone. Th...,0,1,0,0
5,stocks,at://did:plc:xhrtfphu4gzqrztkpb3a63qf/app.bsky...,bafyreie3iucy2lea4s5gm37cyuv4qmxkqk7wgeufpngoc...,babygoldie.bsky.social,did:plc:xhrtfphu4gzqrztkpb3a63qf,2026-06-30T13:05:55.738359+00:00,[1/4] 2026-06-30 19:53:22 - [BlackRock downgra...,0,1,0,0
6,stocks,at://did:plc:xhrtfphu4gzqrztkpb3a63qf/app.bsky...,bafyreiayhvaj2ok6d6dzi5ui3kiq4mtdku75yc2izt5hg...,babygoldie.bsky.social,did:plc:xhrtfphu4gzqrztkpb3a63qf,2026-06-30T13:04:29.172633+00:00,"[3/5] characteristics of ""high scores clusteri...",0,1,0,0
7,stocks,at://did:plc:xhrtfphu4gzqrztkpb3a63qf/app.bsky...,bafyreif55gq3ffvddb4saydqfgtdu5ot37ax6hvs4ljfg...,babygoldie.bsky.social,did:plc:xhrtfphu4gzqrztkpb3a63qf,2026-06-30T13:03:50.262565+00:00,"[3/5] characteristics of ""high scores clusteri...",0,1,0,0
8,stocks,at://did:plc:2mmdgkpha4xuzppdqixd7q6g/app.bsky...,bafyreicmfmna74qb4y7l2dgyyrkh7b2hyvtw7qmgozpma...,aistorynews.bsky.social,did:plc:2mmdgkpha4xuzppdqixd7q6g,2026-06-30T13:03:32Z,"AI chipmaker rally lifts Asia markets, stokes ...",0,0,0,0
9,stocks,at://did:plc:brxtbyqsirrv66f3nqqgkvjz/app.bsky...,bafyreib5lpffxshauieg6vwv6wcyay2dpx5qqumh3ekqi...,chelseafinancial.bsky.social,did:plc:brxtbyqsirrv66f3nqqgkvjz,2026-06-30T06:03:27-07:00,#TechStocks #Stocks #USEconomy #2026Economy #I...,0,0,0,0

In [14]:
# ============================================================
# EXTRACT VALID TICKERS FROM COLLECTED POSTS
# ============================================================

posts_df["tickers"] = posts_df["text"].apply(extract_valid_cashtag_tickers)
posts_df["num_tickers"] = posts_df["tickers"].apply(len)

ticker_posts_df = posts_df[posts_df["num_tickers"] >= 2].copy()
ticker_posts_df = ticker_posts_df.reset_index(drop=True)

print("Total posts:", len(posts_df))
print("Posts with at least 1 valid ticker:", (posts_df["num_tickers"] >= 1).sum())
print("Posts with at least 2 valid tickers:", len(ticker_posts_df))

display(
    ticker_posts_df[["created_at", "author_handle", "text", "tickers", "num_tickers"]]
    .head(20)
)

Total posts: 24766
Posts with at least 1 valid ticker: 4048
Posts with at least 2 valid tickers: 1319

,created_at,author_handle,text,tickers,num_tickers
0,2026-06-30T12:55:33.892Z,chrisversace.bsky.social,Apple’s New iPhone Leaks: 8 Key Items Shaping ...,"[AAPL, NKE, NVDA, PLTR, STZ]",5
1,2026-06-30T12:14:21.366Z,bestsidehustle.bsky.social,"Did you watch $BTC, $ETH, $AAPL, $AMZN repeat ...","[AAPL, AMZN, BTC, ETH]",4
2,2026-06-30T12:01:38.214Z,coingapenews.bsky.social,📈 Ark Invest Doubles Down on Crypto Stocks\n\n...,"[BLSH, COIN, CRCL, HOOD]",4
3,2026-06-30T11:01:02.992Z,iamjaredkim.bsky.social,Citi says 80% of Nasdaq longs are losing. That...,"[IWM, USO]",2
4,2026-06-29T18:37:25.000Z,mikezaccardi.bsky.social,Four Big Questions Facing the Stock Market in ...,"[IWM, MAGS, QQQ, SPY]",4
5,2026-06-30T12:53:14.766Z,coingapenews.bsky.social,📉 #MiCA Deadline Tomorrow\n\nMarkets are watch...,"[BTC, ETH, XRP]",3
6,2026-06-30T10:57:43.932Z,tokenaxishq.bsky.social,"Good morning, traders. 📈\nFinal trading day of...","[AMZN, NKE, STZ]",3
7,2026-06-30T03:36:10.330Z,wallstgamenotes.bsky.social,Can Nike Capitalize On Sports Mania? Q4 Earnin...,"[LULU, NKE]",2
8,2026-06-24T13:09:46.000Z,mikezaccardi.bsky.social,Banks $KBE lit heading into mid-year... and ea...,"[JPM, KBE]",2
9,2026-06-07T11:10:01.564518+00:00,kapualabs.bsky.social,When does a beat become a disappointment? This...,"[AMZN, GOOGL]",2
10,2026-06-01T00:08:40.952Z,stockexpertai.bsky.social,"Retail showing life, but $XRT still lagging th...","[SPY, XRT]",2
11,2026-05-29T10:07:21.327Z,sharesifysocial.bsky.social,Delivered one of the strongest quarterly repor...,"[DELL, NVDA]",2
12,2026-05-28T08:20:15.014Z,mindmathmoney.com,Earnings season is just the market re-pricing ...,"[MRVL, SNOW]",2
13,2026-05-20T12:48:06.644Z,robot2trade.bsky.social,Pre-Market Mayhem Returns!\nGainers: $SLXN +1...,"[GCL, IPW, JUNS, RUBI, SLXN]",5
14,2026-05-18T21:52:59.330Z,robot2trade.bsky.social,"After-Hours Madness! $AMST +87%, $AGYS +14.2%...","[AGYS, AMST, FATN, UBXG]",4
15,2026-05-14T12:10:22.352Z,robot2trade.bsky.social,Pre-market chaos! Top Gainers:\n$SNAL +198.7...,"[AEHL, ALP, DXF, MDXH, SNAL, STAK, WOK, YOOV]",8
16,2026-05-13T13:39:42.577Z,tiernanray.bsky.social,This week and last week tend to be the busiest...,"[DT, NBIS, NXT, TSEM]",4
17,2026-05-11T02:10:01.208Z,equityclock.bsky.social,The loss of earnings season distraction could ...,"[QQQ, SMH, SPY]",3
18,2026-05-07T21:46:46.051Z,robot2trade.bsky.social,Wild after-hours action! Top Gainers:\n$AIIO...,"[AIIO, AKAM, FWRD, HUBS, INOD, KDK]",6
19,2026-05-06T21:21:40.720Z,robot2trade.bsky.social,"AFTER-HOURS MAY 6: $GLE +57%, $OSG +42%, $FLN...","[ADMA, FLNC, FSLY, FTNT, GLE, ONEG, OSG]",7

In [15]:
# ============================================================
# SAVE COLLECTED POSTS
# ============================================================

posts_raw_path = OUTPUT_DIR / "bluesky_posts_raw.csv"
posts_tickers_path = OUTPUT_DIR / "bluesky_posts_with_2plus_tickers.csv"

posts_df.to_csv(posts_raw_path, index=False)
ticker_posts_df.to_csv(posts_tickers_path, index=False)

print("Saved raw posts to:", posts_raw_path)
print("Saved ticker posts to:", posts_tickers_path)

Saved raw posts to: /Users/bucco/Downloads/outputs/bluesky_posts_raw.csv
Saved ticker posts to: /Users/bucco/Downloads/outputs/bluesky_posts_with_2plus_tickers.csv

In [16]:
# ============================================================
# LARGE TICKER-SEEDED QUERY LIST
# ============================================================

# Use broad financial symbols because the goal is a large financial asset co-mention network.
candidate_seed_tickers = sorted(financial_symbols)

# Remove ticker formats that are less likely to work well as Bluesky cashtags/search queries.
# We keep simple symbols first: AAPL, MSFT, NVDA, TSLA, etc.
seed_tickers_simple = [
    t for t in candidate_seed_tickers
    if isinstance(t, str)
    and t.isalnum()
    and 1 <= len(t) <= 5
]

# Optional: remove very short symbols because they can be noisy and ambiguous.
# But keep them if they are in the whitelist. For larger coverage, we keep 1-5 length.
print("Candidate simple seed tickers:", len(seed_tickers_simple))

# Start with 2,000. If this works, increase to 5,000 or 10,000.
N_SEED_TICKERS = 2000

seed_tickers = seed_tickers_simple[:N_SEED_TICKERS]
ticker_seed_queries = [f"${ticker}" for ticker in seed_tickers]

print("Ticker-seeded queries:", len(ticker_seed_queries))
print(ticker_seed_queries[:50])

Candidate simple seed tickers: 12354
Ticker-seeded queries: 2000
['$A', '$AA', '$AAA', '$AAAA', '$AAAC', '$AAAD', '$AAAP', '$AAAU', '$AACB', '$AACBR', '$AACBU', '$AACG', '$AACI', '$AACIU', '$AACIW', '$AACO', '$AACOU', '$AACOW', '$AACP', '$AACPR', '$AACPU', '$AACPW', '$AADR', '$AADX', '$AAEQ', '$AAL', '$AALG', '$AAME', '$AAMI', '$AAOG', '$AAOI', '$AAON', '$AAOX', '$AAP', '$AAPB', '$AAPD', '$AAPG', '$AAPL', '$AAPR', '$AAPU', '$AAPW', '$AAPX', '$AAPY', '$AARD', '$AAT', '$AAUA', '$AAUC', '$AAUM', '$AAUS', '$AAVM']

In [19]:
# ============================================================
# LARGE TICKER-SEEDED QUERY LIST — 10,000 TICKERS
# ============================================================

N_SEED_TICKERS = 10000
MAX_PAGES_PER_QUERY = 5
LIMIT_PER_PAGE = 100

# Keep symbols that are more likely to work well as Bluesky cashtags/search terms.
# Example: AAPL, MSFT, NVDA, TSLA, SPY, QQQ.
seed_tickers_simple = [
    t for t in sorted(financial_symbols)
    if isinstance(t, str)
    and t.isalnum()
    and 1 <= len(t) <= 5
]

# Put highly discussed market symbols first.
priority_tickers = [
    "SPY", "QQQ", "IWM", "DIA", "VTI", "VOO", "TLT", "GLD", "SLV",
    "AAPL", "MSFT", "NVDA", "TSLA", "META", "AMZN", "GOOGL", "GOOG",
    "AMD", "INTC", "NFLX", "AVGO", "ORCL", "PLTR", "SMCI", "COIN",
    "MSTR", "MARA", "RIOT", "CLSK", "HOOD", "JPM", "BAC", "GS", "MS",
    "XOM", "CVX", "OXY", "NKE", "DIS", "UBER", "ABNB", "SHOP", "SQ",
    "PYPL", "BABA", "NIO", "RIVN", "LCID", "SOFI", "GME", "AMC"
]

priority_tickers = [
    t for t in priority_tickers
    if t in seed_tickers_simple
]

remaining_tickers = [
    t for t in seed_tickers_simple
    if t not in set(priority_tickers)
]

seed_tickers = priority_tickers + remaining_tickers
seed_tickers = seed_tickers[:N_SEED_TICKERS]

ticker_seed_queries = [f"${ticker}" for ticker in seed_tickers]

print("Available simple seed tickers:", len(seed_tickers_simple))
print("Ticker-seeded queries selected:", len(ticker_seed_queries))
print("Max theoretical requests:", len(ticker_seed_queries) * MAX_PAGES_PER_QUERY)
print("First 50 queries:")
print(ticker_seed_queries[:50])

Available simple seed tickers: 12354
Ticker-seeded queries selected: 10000
Max theoretical requests: 50000
First 50 queries:
['$SPY', '$QQQ', '$IWM', '$DIA', '$VTI', '$VOO', '$TLT', '$GLD', '$SLV', '$AAPL', '$MSFT', '$NVDA', '$TSLA', '$META', '$AMZN', '$GOOGL', '$GOOG', '$AMD', '$INTC', '$NFLX', '$AVGO', '$ORCL', '$PLTR', '$SMCI', '$COIN', '$MSTR', '$MARA', '$RIOT', '$CLSK', '$HOOD', '$JPM', '$BAC', '$GS', '$MS', '$XOM', '$CVX', '$OXY', '$NKE', '$DIS', '$UBER', '$ABNB', '$SHOP', '$PYPL', '$BABA', '$NIO', '$RIVN', '$LCID', '$SOFI', '$GME', '$AMC']

In [20]:
# ============================================================
# LARGE BLUESKY EXTRACTION — 10,000 TICKERS, 5 PAGES EACH
# WITH CHECKPOINTS, COMPLETED QUERY LOG, AND BACKOFF
# ============================================================

import time
import pandas as pd
from tqdm import tqdm
from pathlib import Path

LARGE_POSTS_CHECKPOINT_PATH = OUTPUT_DIR / "bluesky_large_10000_seeded_posts_checkpoint.csv"
COMPLETED_QUERIES_PATH = OUTPUT_DIR / "bluesky_large_10000_completed_queries.txt"
ERROR_LOG_PATH = OUTPUT_DIR / "bluesky_large_10000_error_log.csv"


def load_completed_queries(path):
    if path.exists():
        with open(path, "r") as f:
            return set(line.strip() for line in f if line.strip())
    return set()


def append_completed_query(path, query):
    with open(path, "a") as f:
        f.write(query + "\n")


def load_posts_checkpoint(path):
    if path.exists():
        df = pd.read_csv(path)
        if "uri" in df.columns:
            df = df.drop_duplicates(subset=["uri"]).reset_index(drop=True)
        print("Loaded post checkpoint:", len(df), "unique posts")
        return df
    return pd.DataFrame()


def save_posts_checkpoint(posts_df, path):
    if len(posts_df) == 0:
        return posts_df

    posts_df = posts_df.drop_duplicates(subset=["uri"]).reset_index(drop=True)
    posts_df.to_csv(path, index=False)
    print("Checkpoint saved:", len(posts_df), "unique posts")
    return posts_df


def append_error_log(path, query, page, error_message):
    row = pd.DataFrame([{
        "query": query,
        "page": page,
        "error": str(error_message),
        "timestamp": pd.Timestamp.utcnow().isoformat()
    }])

    if path.exists():
        old = pd.read_csv(path)
        new = pd.concat([old, row], ignore_index=True)
    else:
        new = row

    new.to_csv(path, index=False)


def search_posts_for_query_big(
    client,
    query,
    max_pages=5,
    limit=100,
    sleep_between_pages=0.5,
    max_retries=3
):
    posts = []
    cursor = None

    for page in range(1, max_pages + 1):
        params = {
            "q": query,
            "limit": limit,
        }

        if cursor:
            params["cursor"] = cursor

        success = False

        for attempt in range(1, max_retries + 1):
            try:
                response = client.app.bsky.feed.search_posts(params)
                success = True
                break

            except Exception as e:
                wait_time = 10 * attempt
                print(f"Error query={query}, page={page}, attempt={attempt}: {e}")
                append_error_log(ERROR_LOG_PATH, query, page, e)
                time.sleep(wait_time)

        if not success:
            break

        response_posts = getattr(response, "posts", [])

        if not response_posts:
            break

        for post in response_posts:
            record = getattr(post, "record", None)
            text = getattr(record, "text", "") if record else ""
            created_at = getattr(record, "created_at", None) if record else None

            posts.append({
                "query": query,
                "uri": getattr(post, "uri", None),
                "cid": getattr(post, "cid", None),
                "author_handle": getattr(post.author, "handle", None),
                "author_did": getattr(post.author, "did", None),
                "created_at": created_at,
                "text": text,
                "like_count": getattr(post, "like_count", 0),
                "reply_count": getattr(post, "reply_count", 0),
                "repost_count": getattr(post, "repost_count", 0),
                "quote_count": getattr(post, "quote_count", 0),
            })

        cursor = getattr(response, "cursor", None)

        if not cursor:
            break

        time.sleep(sleep_between_pages)

    return posts


# Load existing progress if present
completed_queries = load_completed_queries(COMPLETED_QUERIES_PATH)
large_posts_df = load_posts_checkpoint(LARGE_POSTS_CHECKPOINT_PATH)

queries_to_run = [
    q for q in ticker_seed_queries
    if q not in completed_queries
]

print("Total target queries:", len(ticker_seed_queries))
print("Already completed queries:", len(completed_queries))
print("Remaining queries:", len(queries_to_run))
print("Current checkpoint posts:", len(large_posts_df))

SAVE_EVERY_N_QUERIES = 25
SLEEP_BETWEEN_QUERIES = 0.8
LONG_PAUSE_EVERY_N_QUERIES = 250
LONG_PAUSE_SECONDS = 30

new_rows_buffer = []

for i, query in enumerate(tqdm(queries_to_run), start=1):
    query_posts = search_posts_for_query_big(
        client=client,
        query=query,
        max_pages=MAX_PAGES_PER_QUERY,
        limit=LIMIT_PER_PAGE,
        sleep_between_pages=0.5,
        max_retries=3
    )

    if len(query_posts) > 0:
        new_rows_buffer.extend(query_posts)

    append_completed_query(COMPLETED_QUERIES_PATH, query)

    if i % SAVE_EVERY_N_QUERIES == 0:
        if len(new_rows_buffer) > 0:
            buffer_df = pd.DataFrame(new_rows_buffer)
            large_posts_df = pd.concat(
                [large_posts_df, buffer_df],
                ignore_index=True
            )
            new_rows_buffer = []

        large_posts_df = save_posts_checkpoint(
            large_posts_df,
            LARGE_POSTS_CHECKPOINT_PATH
        )

        completed_now = len(load_completed_queries(COMPLETED_QUERIES_PATH))
        print(
            f"Progress: {completed_now}/{len(ticker_seed_queries)} queries completed | "
            f"{len(large_posts_df)} unique posts saved"
        )

    if i % LONG_PAUSE_EVERY_N_QUERIES == 0:
        print(f"Long pause after {i} queries...")
        time.sleep(LONG_PAUSE_SECONDS)

    time.sleep(SLEEP_BETWEEN_QUERIES)


# Final save
if len(new_rows_buffer) > 0:
    buffer_df = pd.DataFrame(new_rows_buffer)
    large_posts_df = pd.concat(
        [large_posts_df, buffer_df],
        ignore_index=True
    )

large_posts_df = save_posts_checkpoint(
    large_posts_df,
    LARGE_POSTS_CHECKPOINT_PATH
)

completed_queries = load_completed_queries(COMPLETED_QUERIES_PATH)

print("DONE.")
print("Completed queries:", len(completed_queries))
print("Large unique posts:", len(large_posts_df))
print("Saved posts checkpoint to:", LARGE_POSTS_CHECKPOINT_PATH)
print("Saved completed queries to:", COMPLETED_QUERIES_PATH)

display(large_posts_df.head(10))

Total target queries: 10000
Already completed queries: 0
Remaining queries: 10000
Current checkpoint posts: 0

  0%|          | 19/10000 [02:18<18:05:40,  6.53s/it]

Error query=$NFLX, page=3, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  0%|          | 20/10000 [02:39<30:36:25, 11.04s/it]

Error query=$AVGO, page=2, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  0%|          | 21/10000 [03:01<39:04:07, 14.09s/it]

Error query=$ORCL, page=5, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  0%|          | 24/10000 [03:38<32:26:01, 11.70s/it]

Checkpoint saved: 11159 unique posts
Progress: 25/10000 queries completed | 11159 unique posts saved

  0%|          | 28/10000 [04:05<21:35:31,  7.80s/it]

Error query=$CLSK, page=3, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  0%|          | 31/10000 [04:44<27:28:27,  9.92s/it]

Error query=$BAC, page=1, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  0%|          | 32/10000 [05:06<37:40:29, 13.61s/it]

Error query=$GS, page=1, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  0%|          | 49/10000 [07:26<17:44:15,  6.42s/it]

Checkpoint saved: 23079 unique posts
Progress: 50/10000 queries completed | 23079 unique posts saved

  0%|          | 50/10000 [07:33<17:47:26,  6.44s/it]

Error query=$A, page=1, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()

Error query=$A, page=1, attempt=2:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()

Error query=$A, page=1, attempt=3:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  1%|          | 74/10000 [10:12<9:17:19,  3.37s/it]

Checkpoint saved: 26392 unique posts
Progress: 75/10000 queries completed | 26392 unique posts saved

  1%|          | 76/10000 [10:27<15:44:51,  5.71s/it]

Error query=$AALG, page=1, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  1%|          | 84/10000 [11:21<15:36:01,  5.66s/it]

Error query=$AAPB, page=1, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  1%|          | 99/10000 [12:25<6:02:41,  2.20s/it]

Checkpoint saved: 31283 unique posts
Progress: 100/10000 queries completed | 31283 unique posts saved

  1%|          | 124/10000 [14:15<15:25:08,  5.62s/it]

Checkpoint saved: 39084 unique posts
Progress: 125/10000 queries completed | 39084 unique posts saved

  1%|▏         | 134/10000 [14:52<7:34:53,  2.77s/it]

Error query=$ACA, page=4, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  1%|▏         | 149/10000 [16:29<18:54:43,  6.91s/it]

Checkpoint saved: 46415 unique posts
Progress: 150/10000 queries completed | 46415 unique posts saved

  2%|▏         | 162/10000 [17:11<10:55:13,  4.00s/it]

Error query=$ACHX, page=1, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  2%|▏         | 172/10000 [18:11<9:05:18,  3.33s/it]

Error query=$ACLS, page=4, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  2%|▏         | 174/10000 [18:35<18:27:26,  6.76s/it]

Checkpoint saved: 52580 unique posts
Progress: 175/10000 queries completed | 52580 unique posts saved

  2%|▏         | 199/10000 [20:59<21:10:54,  7.78s/it]

Checkpoint saved: 60774 unique posts
Progress: 200/10000 queries completed | 60774 unique posts saved

  2%|▏         | 213/10000 [21:44<9:45:26,  3.59s/it]

Error query=$ADAG, page=3, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()

Error query=$ADAG, page=4, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  2%|▏         | 224/10000 [23:03<14:06:05,  5.19s/it]

Checkpoint saved: 66069 unique posts
Progress: 225/10000 queries completed | 66069 unique posts saved

  2%|▏         | 231/10000 [23:49<18:28:38,  6.81s/it]

Error query=$ADGM, page=5, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  2%|▏         | 249/10000 [25:49<17:06:16,  6.31s/it]

Checkpoint saved: 74446 unique posts
Progress: 250/10000 queries completed | 74446 unique posts saved
Long pause after 250 queries...

  3%|▎         | 274/10000 [28:32<16:08:17,  5.97s/it]

Checkpoint saved: 81389 unique posts
Progress: 275/10000 queries completed | 81389 unique posts saved

  3%|▎         | 277/10000 [28:51<16:26:12,  6.09s/it]

Error query=$AER, page=3, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  3%|▎         | 299/10000 [30:47<10:39:43,  3.96s/it]

Checkpoint saved: 88673 unique posts
Progress: 300/10000 queries completed | 88673 unique posts saved

  3%|▎         | 324/10000 [33:05<18:15:55,  6.80s/it]

Checkpoint saved: 96773 unique posts
Progress: 325/10000 queries completed | 96773 unique posts saved

  3%|▎         | 333/10000 [33:54<14:06:16,  5.25s/it]

Error query=$AGM, page=2, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  3%|▎         | 349/10000 [35:02<9:47:06,  3.65s/it]

Checkpoint saved: 101998 unique posts
Progress: 350/10000 queries completed | 101998 unique posts saved

  4%|▎         | 352/10000 [35:09<7:00:14,  2.61s/it]

Error query=$AGRO, page=4, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  4%|▎         | 354/10000 [35:34<17:50:09,  6.66s/it]

Error query=$AGRZ, page=1, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  4%|▎         | 355/10000 [35:51<25:47:30,  9.63s/it]

Error query=$AGX, page=1, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  4%|▎         | 360/10000 [36:24<14:54:42,  5.57s/it]

Error query=$AHD, page=2, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  4%|▎         | 370/10000 [37:39<17:29:38,  6.54s/it]

Error query=$AIAI, page=5, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  4%|▎         | 371/10000 [38:06<33:47:56, 12.64s/it]

Error query=$AIB, page=2, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()

Error query=$AIB, page=2, attempt=2: Response(success=False, status_code=502, content=XrpcError(error='InternalServerError', message='Upstream server responded with a 500 error'), headers={'x-powered-by': 'Express', 'access-control-allow-origin': '*', 'ratelimit-limit': '3000', 'ratelimit-reset': '1782828309', 'ratelimit-remaining': '2996', 'ratelimit-policy': '3000;w=300', 'cache-control': 'private', 'vary': 'Authorization, Accept-Encoding', 'content-type': 'application/json; charset=utf-8', 'content-length': '86', 'etag': 'W/"56-L+jRpk9/y0j/QRmuMywPl8zmsSc"', 'date': 'Tue, 30 Jun 2026 14:00:36 GMT', 'keep-alive': 'timeout=90', 'strict-transport-security': 'max-age=63072000'})

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()

Error query=$AIB, page=3, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()

Error query=$AIB, page=3, attempt=2:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()

Error query=$AIB, page=3, attempt=3:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  4%|▎         | 373/10000 [40:14<89:58:18, 33.64s/it]

Error query=$AIBU, page=1, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  4%|▎         | 374/10000 [40:38<82:41:16, 30.92s/it]

Checkpoint saved: 108912 unique posts
Progress: 375/10000 queries completed | 108912 unique posts saved

  4%|▍         | 376/10000 [40:45<45:21:35, 16.97s/it]

Error query=$AIEQ, page=1, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  4%|▍         | 398/10000 [43:17<14:55:47,  5.60s/it]

Error query=$AIOS, page=3, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  4%|▍         | 399/10000 [43:40<28:28:18, 10.68s/it]

Checkpoint saved: 116887 unique posts
Progress: 400/10000 queries completed | 116887 unique posts saved

  4%|▍         | 402/10000 [44:01<21:15:33,  7.97s/it]

Error query=$AIPO, page=4, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  4%|▍         | 406/10000 [44:41<18:20:22,  6.88s/it]

Error query=$AIR, page=4, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  4%|▍         | 409/10000 [45:29<30:20:23, 11.39s/it]

Error query=$AIRI, page=5, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  4%|▍         | 424/10000 [47:14<14:39:28,  5.51s/it]

Checkpoint saved: 124588 unique posts
Progress: 425/10000 queries completed | 124588 unique posts saved

  4%|▍         | 426/10000 [47:23<12:30:46,  4.71s/it]

Error query=$AIX, page=3, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  4%|▍         | 429/10000 [47:53<19:16:35,  7.25s/it]

Error query=$AIYY, page=1, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  4%|▍         | 430/10000 [48:15<31:06:29, 11.70s/it]

Error query=$AIZ, page=5, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  4%|▍         | 434/10000 [48:53<23:04:19,  8.68s/it]

Error query=$AJUL, page=2, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  4%|▍         | 444/10000 [50:01<11:51:12,  4.47s/it]

Error query=$ALAB, page=4, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  4%|▍         | 449/10000 [50:44<15:30:38,  5.85s/it]

Checkpoint saved: 132939 unique posts
Progress: 450/10000 queries completed | 132939 unique posts saved

  5%|▍         | 466/10000 [51:55<16:03:00,  6.06s/it]

Error query=$ALH, page=3, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  5%|▍         | 474/10000 [52:52<15:45:09,  5.95s/it]

Checkpoint saved: 139941 unique posts
Progress: 475/10000 queries completed | 139941 unique posts saved

  5%|▍         | 476/10000 [53:00<12:47:04,  4.83s/it]

Error query=$ALL, page=3, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()

Error query=$ALL, page=3, attempt=2:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  5%|▍         | 486/10000 [55:07<21:09:25,  8.01s/it]

Error query=$ALMU, page=4, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  5%|▍         | 489/10000 [55:34<19:38:50,  7.44s/it]

Error query=$ALOT, page=3, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  5%|▍         | 499/10000 [56:27<8:54:01,  3.37s/it]

Checkpoint saved: 147202 unique posts
Progress: 500/10000 queries completed | 147202 unique posts saved
Long pause after 500 queries...

  5%|▌         | 509/10000 [57:59<16:57:20,  6.43s/it]

Error query=$ALVO, page=1, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()

Error query=$ALVO, page=1, attempt=2:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  5%|▌         | 523/10000 [1:00:08<20:00:11,  7.60s/it]

Error query=$AMBO, page=2, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  5%|▌         | 524/10000 [1:00:29<30:59:02, 11.77s/it]

Checkpoint saved: 155986 unique posts
Progress: 525/10000 queries completed | 155986 unique posts saved

  5%|▌         | 549/10000 [1:02:15<10:26:26,  3.98s/it]

Checkpoint saved: 162668 unique posts
Progress: 550/10000 queries completed | 162668 unique posts saved

  6%|▌         | 574/10000 [1:04:06<12:15:19,  4.68s/it]

Checkpoint saved: 170262 unique posts
Progress: 575/10000 queries completed | 170262 unique posts saved

  6%|▌         | 599/10000 [1:05:48<16:18:53,  6.25s/it]

Checkpoint saved: 175833 unique posts
Progress: 600/10000 queries completed | 175833 unique posts saved

  6%|▌         | 600/10000 [1:05:57<18:12:46,  6.98s/it]

Error query=$ANEW, page=4, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  6%|▌         | 612/10000 [1:07:27<15:35:19,  5.98s/it]

Error query=$ANNA, page=2, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  6%|▌         | 615/10000 [1:08:07<25:40:49,  9.85s/it]

Error query=$ANPA, page=4, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  6%|▌         | 622/10000 [1:09:25<22:37:31,  8.69s/it]

Error query=$ANV, page=3, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  6%|▌         | 624/10000 [1:10:00<31:44:13, 12.19s/it]

Error query=$ANY, page=2, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()

Error query=$ANY, page=3, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()

Error query=$ANY, page=5, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()

Checkpoint saved: 184521 unique posts
Progress: 625/10000 queries completed | 184521 unique posts saved

  6%|▋         | 629/10000 [1:11:24<25:57:45,  9.97s/it]

Error query=$AOK, page=3, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  6%|▋         | 649/10000 [1:13:33<16:40:36,  6.42s/it]

Checkpoint saved: 192359 unique posts
Progress: 650/10000 queries completed | 192359 unique posts saved

  7%|▋         | 662/10000 [1:14:40<15:32:19,  5.99s/it]

Error query=$APLM, page=1, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  7%|▋         | 674/10000 [1:15:30<9:22:08,  3.62s/it]

Checkpoint saved: 199049 unique posts
Progress: 675/10000 queries completed | 199049 unique posts saved

  7%|▋         | 699/10000 [1:17:23<8:08:51,  3.15s/it]

Checkpoint saved: 205074 unique posts
Progress: 700/10000 queries completed | 205074 unique posts saved

  7%|▋         | 704/10000 [1:17:30<4:46:20,  1.85s/it]

Error query=$AQB, page=1, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  7%|▋         | 715/10000 [1:18:32<16:49:32,  6.52s/it]

Error query=$ARAY, page=5, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  7%|▋         | 724/10000 [1:19:31<14:10:13,  5.50s/it]

Checkpoint saved: 209830 unique posts
Progress: 725/10000 queries completed | 209830 unique posts saved

  7%|▋         | 737/10000 [1:20:13<10:17:33,  4.00s/it]

Error query=$ARE, page=1, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  7%|▋         | 749/10000 [1:21:44<11:12:19,  4.36s/it]

Checkpoint saved: 216490 unique posts
Progress: 750/10000 queries completed | 216490 unique posts saved
Long pause after 750 queries...

  8%|▊         | 760/10000 [1:23:34<28:58:03, 11.29s/it]

Error query=$ARLO, page=1, attempt=1: Response(success=False, status_code=502, content=XrpcError(error='InternalServerError', message='Upstream server responded with a 500 error'), headers={'x-powered-by': 'Express', 'access-control-allow-origin': '*', 'ratelimit-limit': '3000', 'ratelimit-reset': '1782831038', 'ratelimit-remaining': '2998', 'ratelimit-policy': '3000;w=300', 'cache-control': 'private', 'vary': 'Authorization, Accept-Encoding', 'content-type': 'application/json; charset=utf-8', 'content-length': '86', 'etag': 'W/"56-L+jRpk9/y0j/QRmuMywPl8zmsSc"', 'date': 'Tue, 30 Jun 2026 14:45:46 GMT', 'keep-alive': 'timeout=90', 'strict-transport-security': 'max-age=63072000'})

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()

Error query=$ARLO, page=1, attempt=2:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()

Error query=$ARLO, page=1, attempt=3:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  8%|▊         | 761/10000 [1:24:49<77:40:33, 30.27s/it]

Error query=$ARLP, page=1, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()

Error query=$ARLP, page=1, attempt=2:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()

Error query=$ARLP, page=1, attempt=3:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  8%|▊         | 762/10000 [1:26:06<113:38:24, 44.29s/it]

Error query=$ARLU, page=1, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  8%|▊         | 774/10000 [1:27:36<18:03:01,  7.04s/it]

Checkpoint saved: 223354 unique posts
Progress: 775/10000 queries completed | 223354 unique posts saved

  8%|▊         | 799/10000 [1:29:55<17:44:51,  6.94s/it]

Checkpoint saved: 231282 unique posts
Progress: 800/10000 queries completed | 231282 unique posts saved

  8%|▊         | 824/10000 [1:32:00<6:09:40,  2.42s/it]

Checkpoint saved: 239839 unique posts
Progress: 825/10000 queries completed | 239839 unique posts saved

  8%|▊         | 849/10000 [1:33:50<10:38:25,  4.19s/it]

Checkpoint saved: 246295 unique posts
Progress: 850/10000 queries completed | 246295 unique posts saved

  9%|▊         | 874/10000 [1:35:54<11:58:56,  4.73s/it]

Checkpoint saved: 254318 unique posts
Progress: 875/10000 queries completed | 254318 unique posts saved

  9%|▉         | 899/10000 [1:37:37<12:39:46,  5.01s/it]

Checkpoint saved: 260502 unique posts
Progress: 900/10000 queries completed | 260502 unique posts saved

  9%|▉         | 901/10000 [1:37:52<16:28:41,  6.52s/it]

Error query=$AUAU, page=3, attempt=1: Response(success=False, status_code=502, content=XrpcError(error='InternalServerError', message='Upstream server responded with a 500 error'), headers={'x-powered-by': 'Express', 'access-control-allow-origin': '*', 'ratelimit-limit': '3000', 'ratelimit-reset': '1782831640', 'ratelimit-remaining': '2811', 'ratelimit-policy': '3000;w=300', 'cache-control': 'private', 'vary': 'Authorization, Accept-Encoding', 'content-type': 'application/json; charset=utf-8', 'content-length': '86', 'etag': 'W/"56-L+jRpk9/y0j/QRmuMywPl8zmsSc"', 'date': 'Tue, 30 Jun 2026 15:00:08 GMT', 'keep-alive': 'timeout=90', 'strict-transport-security': 'max-age=63072000'})

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  9%|▉         | 902/10000 [1:38:17<30:26:38, 12.05s/it]

Error query=$AUB, page=3, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  9%|▉         | 907/10000 [1:39:19<26:29:53, 10.49s/it]

Error query=$AUGO, page=3, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()

Error query=$AUGO, page=3, attempt=2:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()

Error query=$AUGO, page=3, attempt=3:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  9%|▉         | 908/10000 [3:10:25<4159:57:40, 1647.15s/it]

Error query=$AUGP, page=1, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  9%|▉         | 919/10000 [3:16:37<123:26:05, 48.93s/it]   /var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()

Error query=$AURE, page=1, attempt=1:

  9%|▉         | 924/10000 [3:17:18<35:48:32, 14.20s/it]

Checkpoint saved: 267968 unique posts
Progress: 925/10000 queries completed | 267968 unique posts saved

  9%|▉         | 925/10000 [3:17:21<27:11:30, 10.79s/it]

Error query=$AUUD, page=2, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  9%|▉         | 929/10000 [3:33:30<263:36:38, 104.62s/it]

Error query=$AVAL, page=4, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  9%|▉         | 933/10000 [3:41:00<188:06:56, 74.69s/it]

Error query=$AVB, page=1, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
  9%|▉         | 949/10000 [3:57:42<11:53:49,  4.73s/it]

Checkpoint saved: 275168 unique posts
Progress: 950/10000 queries completed | 275168 unique posts saved

 10%|▉         | 953/10000 [3:57:48<5:17:11,  2.10s/it]

Error query=$AVIE, page=4, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 10%|▉         | 962/10000 [4:14:16<50:07:53, 19.97s/it]

Error query=$AVMA, page=4, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 10%|▉         | 974/10000 [4:30:13<24:04:53,  9.60s/it]

Checkpoint saved: 280487 unique posts
Progress: 975/10000 queries completed | 280487 unique posts saved

 10%|▉         | 999/10000 [4:31:57<15:55:25,  6.37s/it]

Checkpoint saved: 287248 unique posts
Progress: 1000/10000 queries completed | 287248 unique posts saved
Long pause after 1000 queries...

 10%|█         | 1024/10000 [4:34:19<9:50:27,  3.95s/it]

Checkpoint saved: 293928 unique posts
Progress: 1025/10000 queries completed | 293928 unique posts saved

 10%|█         | 1049/10000 [4:36:31<7:30:16,  3.02s/it]

Checkpoint saved: 301679 unique posts
Progress: 1050/10000 queries completed | 301679 unique posts saved

 11%|█         | 1074/10000 [4:39:06<11:10:47,  4.51s/it]

Checkpoint saved: 309665 unique posts
Progress: 1075/10000 queries completed | 309665 unique posts saved

 11%|█         | 1080/10000 [4:39:50<19:10:16,  7.74s/it]

Error query=$BARK, page=3, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 11%|█         | 1099/10000 [4:42:31<9:51:16,  3.99s/it]

Checkpoint saved: 318175 unique posts
Progress: 1100/10000 queries completed | 318175 unique posts saved

 11%|█         | 1124/10000 [4:44:11<6:07:27,  2.48s/it]

Checkpoint saved: 323275 unique posts
Progress: 1125/10000 queries completed | 323275 unique posts saved

 11%|█▏        | 1149/10000 [4:45:50<10:57:32,  4.46s/it]

Checkpoint saved: 329698 unique posts
Progress: 1150/10000 queries completed | 329698 unique posts saved

 12%|█▏        | 1174/10000 [4:47:12<6:55:25,  2.82s/it]

Checkpoint saved: 334951 unique posts
Progress: 1175/10000 queries completed | 334951 unique posts saved

 12%|█▏        | 1199/10000 [4:48:43<7:43:35,  3.16s/it]

Checkpoint saved: 339709 unique posts
Progress: 1200/10000 queries completed | 339709 unique posts saved

 12%|█▏        | 1224/10000 [4:50:37<18:47:34,  7.71s/it]

Checkpoint saved: 344359 unique posts
Progress: 1225/10000 queries completed | 344359 unique posts saved

 12%|█▏        | 1249/10000 [4:52:44<9:23:49,  3.87s/it]

Checkpoint saved: 352372 unique posts
Progress: 1250/10000 queries completed | 352372 unique posts saved
Long pause after 1250 queries...

 13%|█▎        | 1251/10000 [4:53:26<27:58:43, 11.51s/it]

Error query=$BESO, page=4, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()

Error query=$BESO, page=4, attempt=2: Response(success=False, status_code=502, content=XrpcError(error='InternalServerError', message='Upstream server responded with a 500 error'), headers={'x-powered-by': 'Express', 'access-control-allow-origin': '*', 'ratelimit-limit': '3000', 'ratelimit-reset': '1782843409', 'ratelimit-remaining': '2876', 'ratelimit-policy': '3000;w=300', 'cache-control': 'private', 'vary': 'Authorization, Accept-Encoding', 'content-type': 'application/json; charset=utf-8', 'content-length': '86', 'etag': 'W/"56-L+jRpk9/y0j/QRmuMywPl8zmsSc"', 'date': 'Tue, 30 Jun 2026 18:16:01 GMT', 'keep-alive': 'timeout=90', 'strict-transport-security': 'max-age=63072000'})

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 13%|█▎        | 1274/10000 [4:56:17<5:39:05,  2.33s/it]

Checkpoint saved: 358836 unique posts
Progress: 1275/10000 queries completed | 358836 unique posts saved

 13%|█▎        | 1299/10000 [4:57:49<10:32:23,  4.36s/it]

Checkpoint saved: 363440 unique posts
Progress: 1300/10000 queries completed | 363440 unique posts saved

 13%|█▎        | 1324/10000 [5:01:11<6:48:18,  2.82s/it]

Checkpoint saved: 369615 unique posts
Progress: 1325/10000 queries completed | 369615 unique posts saved

 13%|█▎        | 1349/10000 [5:03:03<14:53:58,  6.20s/it]

Checkpoint saved: 377737 unique posts
Progress: 1350/10000 queries completed | 377737 unique posts saved

 14%|█▎        | 1374/10000 [5:05:34<12:55:53,  5.40s/it]

Checkpoint saved: 386836 unique posts
Progress: 1375/10000 queries completed | 386836 unique posts saved

 14%|█▍        | 1399/10000 [5:07:06<3:18:16,  1.38s/it]

Checkpoint saved: 391630 unique posts
Progress: 1400/10000 queries completed | 391630 unique posts saved

 14%|█▍        | 1424/10000 [5:08:57<22:36:57,  9.49s/it]

Checkpoint saved: 395084 unique posts
Progress: 1425/10000 queries completed | 395084 unique posts saved

 14%|█▍        | 1449/10000 [5:10:48<7:12:26,  3.03s/it]

Checkpoint saved: 401321 unique posts
Progress: 1450/10000 queries completed | 401321 unique posts saved

 15%|█▍        | 1474/10000 [5:12:20<8:55:04,  3.77s/it]

Checkpoint saved: 406568 unique posts
Progress: 1475/10000 queries completed | 406568 unique posts saved

 15%|█▍        | 1499/10000 [5:13:44<7:39:18,  3.24s/it]

Checkpoint saved: 411893 unique posts
Progress: 1500/10000 queries completed | 411893 unique posts saved
Long pause after 1500 queries...

 15%|█▌        | 1524/10000 [5:15:37<8:38:50,  3.67s/it]

Checkpoint saved: 416195 unique posts
Progress: 1525/10000 queries completed | 416195 unique posts saved

 15%|█▌        | 1549/10000 [5:17:30<13:38:11,  5.81s/it]

Checkpoint saved: 424128 unique posts
Progress: 1550/10000 queries completed | 424128 unique posts saved

 16%|█▌        | 1574/10000 [5:20:10<7:20:43,  3.14s/it]

Checkpoint saved: 433517 unique posts
Progress: 1575/10000 queries completed | 433517 unique posts saved

 16%|█▌        | 1599/10000 [5:21:48<10:44:58,  4.61s/it]

Checkpoint saved: 440144 unique posts
Progress: 1600/10000 queries completed | 440144 unique posts saved

 16%|█▌        | 1624/10000 [5:23:14<4:47:28,  2.06s/it]

Checkpoint saved: 445499 unique posts
Progress: 1625/10000 queries completed | 445499 unique posts saved

 16%|█▋        | 1649/10000 [5:24:58<7:09:51,  3.09s/it]

Checkpoint saved: 451890 unique posts
Progress: 1650/10000 queries completed | 451890 unique posts saved

 17%|█▋        | 1674/10000 [5:25:41<2:44:54,  1.19s/it]

Checkpoint saved: 453496 unique posts
Progress: 1675/10000 queries completed | 453496 unique posts saved

 17%|█▋        | 1699/10000 [5:26:58<6:11:26,  2.68s/it]

Checkpoint saved: 457728 unique posts
Progress: 1700/10000 queries completed | 457728 unique posts saved

 17%|█▋        | 1724/10000 [5:28:45<10:57:42,  4.77s/it]

Checkpoint saved: 463477 unique posts
Progress: 1725/10000 queries completed | 463477 unique posts saved

 17%|█▋        | 1749/10000 [5:30:48<7:31:04,  3.28s/it]

Checkpoint saved: 471110 unique posts
Progress: 1750/10000 queries completed | 471110 unique posts saved
Long pause after 1750 queries...

 18%|█▊        | 1774/10000 [5:32:57<11:05:51,  4.86s/it]

Checkpoint saved: 477581 unique posts
Progress: 1775/10000 queries completed | 477581 unique posts saved

 18%|█▊        | 1799/10000 [5:34:34<5:15:13,  2.31s/it]

Checkpoint saved: 484001 unique posts
Progress: 1800/10000 queries completed | 484001 unique posts saved

 18%|█▊        | 1824/10000 [5:36:18<7:38:27,  3.36s/it]

Checkpoint saved: 490208 unique posts
Progress: 1825/10000 queries completed | 490208 unique posts saved

 18%|█▊        | 1849/10000 [5:38:38<15:23:53,  6.80s/it]

Checkpoint saved: 499022 unique posts
Progress: 1850/10000 queries completed | 499022 unique posts saved

 19%|█▊        | 1869/10000 [5:41:57<30:11:48, 13.37s/it]

Error query=$CAMX, page=1, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 19%|█▊        | 1874/10000 [5:42:59<24:37:42, 10.91s/it]

Checkpoint saved: 508736 unique posts
Progress: 1875/10000 queries completed | 508736 unique posts saved

 19%|█▉        | 1899/10000 [5:45:46<17:30:36,  7.78s/it]

Checkpoint saved: 517627 unique posts
Progress: 1900/10000 queries completed | 517627 unique posts saved

 19%|█▉        | 1924/10000 [5:48:24<10:33:11,  4.70s/it]

Checkpoint saved: 526351 unique posts
Progress: 1925/10000 queries completed | 526351 unique posts saved

 19%|█▉        | 1949/10000 [5:49:43<4:20:10,  1.94s/it]

Checkpoint saved: 531579 unique posts
Progress: 1950/10000 queries completed | 531579 unique posts saved

 20%|█▉        | 1974/10000 [5:51:12<6:25:56,  2.89s/it]

Checkpoint saved: 537032 unique posts
Progress: 1975/10000 queries completed | 537032 unique posts saved

 20%|█▉        | 1999/10000 [5:52:37<6:56:04,  3.12s/it]

Checkpoint saved: 542368 unique posts
Progress: 2000/10000 queries completed | 542368 unique posts saved
Long pause after 2000 queries...

 20%|██        | 2024/10000 [5:54:56<10:47:55,  4.87s/it]

Checkpoint saved: 548684 unique posts
Progress: 2025/10000 queries completed | 548684 unique posts saved

 20%|██        | 2049/10000 [5:57:07<10:54:43,  4.94s/it]

Checkpoint saved: 554859 unique posts
Progress: 2050/10000 queries completed | 554859 unique posts saved

 21%|██        | 2074/10000 [5:59:33<14:06:54,  6.41s/it]

Checkpoint saved: 563495 unique posts
Progress: 2075/10000 queries completed | 563495 unique posts saved

 21%|██        | 2099/10000 [6:01:00<4:29:18,  2.05s/it]

Checkpoint saved: 567488 unique posts
Progress: 2100/10000 queries completed | 567488 unique posts saved

 21%|██        | 2109/10000 [6:01:42<10:12:58,  4.66s/it]

Error query=$CGNT, page=1, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 21%|██        | 2124/10000 [6:02:50<7:02:10,  3.22s/it]

Checkpoint saved: 570391 unique posts
Progress: 2125/10000 queries completed | 570391 unique posts saved

 21%|██▏       | 2149/10000 [6:05:09<8:25:01,  3.86s/it]

Checkpoint saved: 578590 unique posts
Progress: 2150/10000 queries completed | 578590 unique posts saved

 22%|██▏       | 2174/10000 [6:06:38<9:16:42,  4.27s/it]

Checkpoint saved: 583846 unique posts
Progress: 2175/10000 queries completed | 583846 unique posts saved

 22%|██▏       | 2188/10000 [6:07:54<7:09:21,  3.30s/it]

Error query=$CIEN, page=2, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()

Error query=$CIEN, page=2, attempt=2:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()

Error query=$CIEN, page=2, attempt=3:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 22%|██▏       | 2189/10000 [6:09:12<56:12:19, 25.90s/it]

Error query=$CIFC, page=1, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()

Error query=$CIFC, page=1, attempt=2:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()

Error query=$CIFC, page=1, attempt=3:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 22%|██▏       | 2199/10000 [6:11:27<16:40:28,  7.69s/it]

Checkpoint saved: 591311 unique posts
Progress: 2200/10000 queries completed | 591311 unique posts saved

 22%|██▏       | 2224/10000 [6:13:19<7:34:43,  3.51s/it]

Checkpoint saved: 598274 unique posts
Progress: 2225/10000 queries completed | 598274 unique posts saved

 22%|██▏       | 2249/10000 [6:15:22<15:06:45,  7.02s/it]

Checkpoint saved: 606012 unique posts
Progress: 2250/10000 queries completed | 606012 unique posts saved
Long pause after 2250 queries...

 23%|██▎       | 2274/10000 [6:17:45<8:41:42,  4.05s/it]

Checkpoint saved: 611773 unique posts
Progress: 2275/10000 queries completed | 611773 unique posts saved

 23%|██▎       | 2299/10000 [6:19:55<10:45:58,  5.03s/it]

Checkpoint saved: 618622 unique posts
Progress: 2300/10000 queries completed | 618622 unique posts saved

 23%|██▎       | 2324/10000 [6:21:37<10:39:44,  5.00s/it]

Checkpoint saved: 625192 unique posts
Progress: 2325/10000 queries completed | 625192 unique posts saved

 23%|██▎       | 2349/10000 [6:23:10<4:59:20,  2.35s/it]

Checkpoint saved: 630786 unique posts
Progress: 2350/10000 queries completed | 630786 unique posts saved

 24%|██▎       | 2374/10000 [6:25:29<12:49:49,  6.06s/it]

Checkpoint saved: 639177 unique posts
Progress: 2375/10000 queries completed | 639177 unique posts saved

 24%|██▍       | 2399/10000 [6:28:14<9:45:08,  4.62s/it]

Checkpoint saved: 649570 unique posts
Progress: 2400/10000 queries completed | 649570 unique posts saved

 24%|██▍       | 2424/10000 [6:30:33<10:42:45,  5.09s/it]

Checkpoint saved: 658278 unique posts
Progress: 2425/10000 queries completed | 658278 unique posts saved

 24%|██▍       | 2449/10000 [6:32:08<6:32:40,  3.12s/it]

Checkpoint saved: 663920 unique posts
Progress: 2450/10000 queries completed | 663920 unique posts saved

 25%|██▍       | 2474/10000 [6:33:28<6:33:54,  3.14s/it]

Checkpoint saved: 669224 unique posts
Progress: 2475/10000 queries completed | 669224 unique posts saved

 25%|██▍       | 2499/10000 [6:34:51<7:00:15,  3.36s/it]

Checkpoint saved: 673856 unique posts
Progress: 2500/10000 queries completed | 673856 unique posts saved
Long pause after 2500 queries...

 25%|██▌       | 2524/10000 [6:36:59<10:18:28,  4.96s/it]

Checkpoint saved: 680327 unique posts
Progress: 2525/10000 queries completed | 680327 unique posts saved

 25%|██▌       | 2549/10000 [6:39:14<14:09:40,  6.84s/it]

Checkpoint saved: 687229 unique posts
Progress: 2550/10000 queries completed | 687229 unique posts saved

 26%|██▌       | 2556/10000 [6:40:13<15:40:07,  7.58s/it]

Error query=$CRWL, page=1, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 26%|██▌       | 2574/10000 [6:42:10<9:43:35,  4.72s/it]

Checkpoint saved: 693774 unique posts
Progress: 2575/10000 queries completed | 693774 unique posts saved

 26%|██▌       | 2599/10000 [6:44:06<9:15:46,  4.51s/it]

Checkpoint saved: 701044 unique posts
Progress: 2600/10000 queries completed | 701044 unique posts saved

 26%|██▌       | 2624/10000 [6:45:27<11:04:53,  5.41s/it]

Checkpoint saved: 705589 unique posts
Progress: 2625/10000 queries completed | 705589 unique posts saved

 26%|██▋       | 2649/10000 [6:47:29<10:29:01,  5.13s/it]

Checkpoint saved: 713864 unique posts
Progress: 2650/10000 queries completed | 713864 unique posts saved

 27%|██▋       | 2674/10000 [6:49:20<6:29:48,  3.19s/it]

Checkpoint saved: 720269 unique posts
Progress: 2675/10000 queries completed | 720269 unique posts saved

 27%|██▋       | 2699/10000 [6:51:10<6:24:03,  3.16s/it]

Checkpoint saved: 727091 unique posts
Progress: 2700/10000 queries completed | 727091 unique posts saved

 27%|██▋       | 2724/10000 [6:52:35<6:30:40,  3.22s/it]

Checkpoint saved: 732749 unique posts
Progress: 2725/10000 queries completed | 732749 unique posts saved

 27%|██▋       | 2749/10000 [6:55:10<15:51:31,  7.87s/it]

Checkpoint saved: 741625 unique posts
Progress: 2750/10000 queries completed | 741625 unique posts saved
Long pause after 2750 queries...

 28%|██▊       | 2774/10000 [6:57:29<5:02:27,  2.51s/it]

Checkpoint saved: 748341 unique posts
Progress: 2775/10000 queries completed | 748341 unique posts saved

 28%|██▊       | 2799/10000 [6:59:30<7:30:14,  3.75s/it]

Checkpoint saved: 755442 unique posts
Progress: 2800/10000 queries completed | 755442 unique posts saved

 28%|██▊       | 2824/10000 [7:00:42<3:32:49,  1.78s/it]

Checkpoint saved: 759328 unique posts
Progress: 2825/10000 queries completed | 759328 unique posts saved

 28%|██▊       | 2849/10000 [7:02:41<11:30:31,  5.79s/it]

Checkpoint saved: 766206 unique posts
Progress: 2850/10000 queries completed | 766206 unique posts saved

 29%|██▊       | 2874/10000 [7:05:04<5:14:05,  2.64s/it]

Checkpoint saved: 773919 unique posts
Progress: 2875/10000 queries completed | 773919 unique posts saved

 29%|██▉       | 2899/10000 [7:06:11<3:13:04,  1.63s/it]

Checkpoint saved: 776624 unique posts
Progress: 2900/10000 queries completed | 776624 unique posts saved

 29%|██▉       | 2910/10000 [7:06:36<2:43:06,  1.38s/it]

Error query=$DFSV, page=1, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 29%|██▉       | 2924/10000 [7:07:22<4:00:06,  2.04s/it]

Checkpoint saved: 778910 unique posts
Progress: 2925/10000 queries completed | 778910 unique posts saved

 29%|██▉       | 2949/10000 [7:09:20<8:59:24,  4.59s/it]

Checkpoint saved: 784896 unique posts
Progress: 2950/10000 queries completed | 784896 unique posts saved

 30%|██▉       | 2974/10000 [7:11:51<7:56:44,  4.07s/it]

Checkpoint saved: 793603 unique posts
Progress: 2975/10000 queries completed | 793603 unique posts saved

 30%|██▉       | 2999/10000 [7:13:44<7:23:34,  3.80s/it]

Checkpoint saved: 800853 unique posts
Progress: 3000/10000 queries completed | 800853 unique posts saved
Long pause after 3000 queries...

 30%|███       | 3024/10000 [7:15:51<8:28:52,  4.38s/it]

Checkpoint saved: 806464 unique posts
Progress: 3025/10000 queries completed | 806464 unique posts saved

 30%|███       | 3049/10000 [7:17:15<6:18:36,  3.27s/it]

Checkpoint saved: 811468 unique posts
Progress: 3050/10000 queries completed | 811468 unique posts saved

 31%|███       | 3074/10000 [7:20:03<10:34:33,  5.50s/it]

Checkpoint saved: 821984 unique posts
Progress: 3075/10000 queries completed | 821984 unique posts saved

 31%|███       | 3099/10000 [7:22:00<8:06:58,  4.23s/it]

Checkpoint saved: 829317 unique posts
Progress: 3100/10000 queries completed | 829317 unique posts saved

 31%|███       | 3120/10000 [7:23:22<7:12:21,  3.77s/it]

Error query=$DSGX, page=1, attempt=1: Response(success=False, status_code=502, content=XrpcError(error='InternalServerError', message='Upstream server responded with a 500 error'), headers={'x-powered-by': 'Express', 'access-control-allow-origin': '*', 'ratelimit-limit': '3000', 'ratelimit-reset': '1782852507', 'ratelimit-remaining': '2911', 'ratelimit-policy': '3000;w=300', 'cache-control': 'private', 'vary': 'Authorization, Accept-Encoding', 'content-type': 'application/json; charset=utf-8', 'content-length': '86', 'etag': 'W/"56-L+jRpk9/y0j/QRmuMywPl8zmsSc"', 'date': 'Tue, 30 Jun 2026 20:45:34 GMT', 'keep-alive': 'timeout=90', 'strict-transport-security': 'max-age=63072000'})

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 31%|███       | 3124/10000 [7:24:12<18:26:14,  9.65s/it]

Checkpoint saved: 835073 unique posts
Progress: 3125/10000 queries completed | 835073 unique posts saved

 31%|███▏      | 3132/10000 [7:25:07<11:41:58,  6.13s/it]

Error query=$DSX, page=4, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 31%|███▏      | 3149/10000 [7:27:02<10:25:13,  5.48s/it]

Checkpoint saved: 843776 unique posts
Progress: 3150/10000 queries completed | 843776 unique posts saved

 32%|███▏      | 3174/10000 [7:28:38<7:53:46,  4.16s/it]

Checkpoint saved: 849368 unique posts
Progress: 3175/10000 queries completed | 849368 unique posts saved

 32%|███▏      | 3199/10000 [7:30:04<2:30:26,  1.33s/it]

Checkpoint saved: 853728 unique posts
Progress: 3200/10000 queries completed | 853728 unique posts saved

 32%|███▏      | 3224/10000 [7:31:25<10:25:55,  5.54s/it]

Checkpoint saved: 858360 unique posts
Progress: 3225/10000 queries completed | 858360 unique posts saved

 32%|███▏      | 3249/10000 [7:32:49<9:32:30,  5.09s/it]

Checkpoint saved: 863056 unique posts
Progress: 3250/10000 queries completed | 863056 unique posts saved
Long pause after 3250 queries...

 33%|███▎      | 3274/10000 [7:35:17<9:05:36,  4.87s/it]

Checkpoint saved: 870071 unique posts
Progress: 3275/10000 queries completed | 870071 unique posts saved

 33%|███▎      | 3299/10000 [7:37:25<8:06:01,  4.35s/it]

Checkpoint saved: 878907 unique posts
Progress: 3300/10000 queries completed | 878907 unique posts saved

 33%|███▎      | 3305/10000 [7:38:01<10:50:09,  5.83s/it]

Error query=$EDEN, page=2, attempt=1: Response(success=False, status_code=502, content=XrpcError(error='InternalServerError', message='Upstream server responded with a 500 error'), headers={'x-powered-by': 'Express', 'access-control-allow-origin': '*', 'ratelimit-limit': '3000', 'ratelimit-reset': '1782853410', 'ratelimit-remaining': '2928', 'ratelimit-policy': '3000;w=300', 'cache-control': 'private', 'vary': 'Authorization, Accept-Encoding', 'content-type': 'application/json; charset=utf-8', 'content-length': '86', 'etag': 'W/"56-L+jRpk9/y0j/QRmuMywPl8zmsSc"', 'date': 'Tue, 30 Jun 2026 21:00:16 GMT', 'keep-alive': 'timeout=90', 'strict-transport-security': 'max-age=63072000'})

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()

Error query=$EDEN, page=2, attempt=2: Response(success=False, status_code=502, content=XrpcError(error='InternalServerError', message='Upstream server responded with a 500 error'), headers={'x-powered-by': 'Express', 'access-control-allow-origin': '*', 'ratelimit-limit': '3000', 'ratelimit-reset': '1782853410', 'ratelimit-remaining': '2927', 'ratelimit-policy': '3000;w=300', 'cache-control': 'private', 'vary': 'Authorization, Accept-Encoding', 'content-type': 'application/json; charset=utf-8', 'content-length': '86', 'etag': 'W/"56-L+jRpk9/y0j/QRmuMywPl8zmsSc"', 'date': 'Tue, 30 Jun 2026 21:00:30 GMT', 'keep-alive': 'timeout=90', 'strict-transport-security': 'max-age=63072000'})

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()

Error query=$EDEN, page=4, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 33%|███▎      | 3307/10000 [7:39:31<43:49:42, 23.57s/it]

Error query=$EDGE, page=1, attempt=1: Response(success=False, status_code=502, content=XrpcError(error='InternalServerError', message='Upstream server responded with a 500 error'), headers={'x-powered-by': 'Express', 'access-control-allow-origin': '*', 'ratelimit-limit': '3000', 'ratelimit-reset': '1782853410', 'ratelimit-remaining': '2917', 'ratelimit-policy': '3000;w=300', 'cache-control': 'private', 'vary': 'Authorization, Accept-Encoding', 'content-type': 'application/json; charset=utf-8', 'content-length': '86', 'etag': 'W/"56-L+jRpk9/y0j/QRmuMywPl8zmsSc"', 'date': 'Tue, 30 Jun 2026 21:01:44 GMT', 'keep-alive': 'timeout=90', 'strict-transport-security': 'max-age=63072000'})

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()

Error query=$EDGE, page=1, attempt=2:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 33%|███▎      | 3324/10000 [7:41:27<9:09:41,  4.94s/it]

Checkpoint saved: 884751 unique posts
Progress: 3325/10000 queries completed | 884751 unique posts saved

 33%|███▎      | 3349/10000 [7:43:29<5:58:00,  3.23s/it]

Checkpoint saved: 892995 unique posts
Progress: 3350/10000 queries completed | 892995 unique posts saved

 34%|███▎      | 3374/10000 [7:45:32<8:05:27,  4.40s/it]

Checkpoint saved: 900868 unique posts
Progress: 3375/10000 queries completed | 900868 unique posts saved

 34%|███▍      | 3399/10000 [7:47:26<8:50:22,  4.82s/it]

Checkpoint saved: 907756 unique posts
Progress: 3400/10000 queries completed | 907756 unique posts saved

 34%|███▍      | 3424/10000 [7:49:30<11:24:38,  6.25s/it]

Checkpoint saved: 915193 unique posts
Progress: 3425/10000 queries completed | 915193 unique posts saved

 34%|███▍      | 3449/10000 [7:51:28<7:45:07,  4.26s/it]

Checkpoint saved: 922090 unique posts
Progress: 3450/10000 queries completed | 922090 unique posts saved

 35%|███▍      | 3474/10000 [7:53:03<4:51:00,  2.68s/it]

Checkpoint saved: 927458 unique posts
Progress: 3475/10000 queries completed | 927458 unique posts saved

 35%|███▍      | 3499/10000 [7:54:38<3:22:41,  1.87s/it]

Checkpoint saved: 933235 unique posts
Progress: 3500/10000 queries completed | 933235 unique posts saved
Long pause after 3500 queries...

 35%|███▌      | 3524/10000 [7:56:57<7:23:39,  4.11s/it]

Checkpoint saved: 939630 unique posts
Progress: 3525/10000 queries completed | 939630 unique posts saved

 35%|███▌      | 3549/10000 [7:58:57<8:58:03,  5.00s/it]

Checkpoint saved: 947205 unique posts
Progress: 3550/10000 queries completed | 947205 unique posts saved

 36%|███▌      | 3574/10000 [8:00:41<6:00:46,  3.37s/it]

Checkpoint saved: 953653 unique posts
Progress: 3575/10000 queries completed | 953653 unique posts saved

 36%|███▌      | 3599/10000 [8:02:41<9:02:23,  5.08s/it]

Checkpoint saved: 961545 unique posts
Progress: 3600/10000 queries completed | 961545 unique posts saved

 36%|███▌      | 3624/10000 [8:04:26<5:05:36,  2.88s/it]

Checkpoint saved: 966977 unique posts
Progress: 3625/10000 queries completed | 966977 unique posts saved

 36%|███▋      | 3649/10000 [8:06:37<6:38:23,  3.76s/it]

Checkpoint saved: 974984 unique posts
Progress: 3650/10000 queries completed | 974984 unique posts saved

 37%|███▋      | 3674/10000 [8:08:50<5:16:41,  3.00s/it]

Checkpoint saved: 983129 unique posts
Progress: 3675/10000 queries completed | 983129 unique posts saved

 37%|███▋      | 3699/10000 [8:10:40<8:02:30,  4.59s/it]

Checkpoint saved: 989387 unique posts
Progress: 3700/10000 queries completed | 989387 unique posts saved

 37%|███▋      | 3724/10000 [8:11:58<4:44:51,  2.72s/it]

Checkpoint saved: 994254 unique posts
Progress: 3725/10000 queries completed | 994254 unique posts saved

 37%|███▋      | 3749/10000 [8:14:05<8:53:33,  5.12s/it]

Checkpoint saved: 1003109 unique posts
Progress: 3750/10000 queries completed | 1003109 unique posts saved
Long pause after 3750 queries...

 38%|███▊      | 3774/10000 [8:16:38<9:43:10,  5.62s/it]

Checkpoint saved: 1011550 unique posts
Progress: 3775/10000 queries completed | 1011550 unique posts saved

 38%|███▊      | 3799/10000 [8:18:44<11:30:05,  6.68s/it]

Checkpoint saved: 1018172 unique posts
Progress: 3800/10000 queries completed | 1018172 unique posts saved

 38%|███▊      | 3824/10000 [8:21:13<11:28:51,  6.69s/it]

Checkpoint saved: 1026186 unique posts
Progress: 3825/10000 queries completed | 1026186 unique posts saved

 38%|███▊      | 3849/10000 [8:22:30<4:26:22,  2.60s/it]

Checkpoint saved: 1030354 unique posts
Progress: 3850/10000 queries completed | 1030354 unique posts saved

 39%|███▊      | 3874/10000 [8:24:10<5:10:50,  3.04s/it]

Checkpoint saved: 1035138 unique posts
Progress: 3875/10000 queries completed | 1035138 unique posts saved

 39%|███▉      | 3899/10000 [8:25:24<4:00:19,  2.36s/it]

Checkpoint saved: 1038557 unique posts
Progress: 3900/10000 queries completed | 1038557 unique posts saved

 39%|███▉      | 3924/10000 [8:26:44<6:31:19,  3.86s/it]

Checkpoint saved: 1043097 unique posts
Progress: 3925/10000 queries completed | 1043097 unique posts saved

 39%|███▉      | 3949/10000 [8:28:35<6:09:24,  3.66s/it]

Checkpoint saved: 1049490 unique posts
Progress: 3950/10000 queries completed | 1049490 unique posts saved

 40%|███▉      | 3974/10000 [8:30:47<10:36:07,  6.33s/it]

Checkpoint saved: 1058159 unique posts
Progress: 3975/10000 queries completed | 1058159 unique posts saved

 40%|███▉      | 3999/10000 [8:31:54<3:11:36,  1.92s/it]

Checkpoint saved: 1061824 unique posts
Progress: 4000/10000 queries completed | 1061824 unique posts saved
Long pause after 4000 queries...

 40%|████      | 4024/10000 [8:33:41<4:03:18,  2.44s/it]

Checkpoint saved: 1065477 unique posts
Progress: 4025/10000 queries completed | 1065477 unique posts saved

 40%|████      | 4049/10000 [8:35:27<6:06:57,  3.70s/it]

Checkpoint saved: 1071059 unique posts
Progress: 4050/10000 queries completed | 1071059 unique posts saved

 41%|████      | 4074/10000 [8:37:24<5:40:38,  3.45s/it]

Checkpoint saved: 1078706 unique posts
Progress: 4075/10000 queries completed | 1078706 unique posts saved

 41%|████      | 4099/10000 [8:39:06<5:48:21,  3.54s/it]

Checkpoint saved: 1082939 unique posts
Progress: 4100/10000 queries completed | 1082939 unique posts saved

 41%|████      | 4107/10000 [8:40:18<10:18:39,  6.30s/it]

Error query=$FLGV, page=1, attempt=1: Response(success=False, status_code=502, content=XrpcError(error='InternalServerError', message='Upstream server responded with a 500 error'), headers={'x-powered-by': 'Express', 'access-control-allow-origin': '*', 'ratelimit-limit': '3000', 'ratelimit-reset': '1782857016', 'ratelimit-remaining': '2873', 'ratelimit-policy': '3000;w=300', 'cache-control': 'private', 'vary': 'Authorization, Accept-Encoding', 'content-type': 'application/json; charset=utf-8', 'content-length': '86', 'etag': 'W/"56-L+jRpk9/y0j/QRmuMywPl8zmsSc"', 'date': 'Tue, 30 Jun 2026 22:02:30 GMT', 'keep-alive': 'timeout=90', 'strict-transport-security': 'max-age=63072000'})

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 41%|████      | 4110/10000 [8:41:00<19:04:37, 11.66s/it]

Error query=$FLIN, page=4, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()

Error query=$FLIN, page=5, attempt=1: Response(success=False, status_code=502, content=XrpcError(error='InternalServerError', message='Upstream server responded with a 500 error'), headers={'x-powered-by': 'Express', 'access-control-allow-origin': '*', 'ratelimit-limit': '3000', 'ratelimit-reset': '1782857317', 'ratelimit-remaining': '2998', 'ratelimit-policy': '3000;w=300', 'cache-control': 'private', 'vary': 'Authorization, Accept-Encoding', 'content-type': 'application/json; charset=utf-8', 'content-length': '86', 'etag': 'W/"56-L+jRpk9/y0j/QRmuMywPl8zmsSc"', 'date': 'Tue, 30 Jun 2026 22:03:44 GMT', 'keep-alive': 'timeout=90', 'strict-transport-security': 'max-age=63072000'})

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 41%|████      | 4124/10000 [8:42:45<8:52:55,  5.44s/it]

Checkpoint saved: 1088117 unique posts
Progress: 4125/10000 queries completed | 1088117 unique posts saved

 41%|████▏     | 4149/10000 [8:44:46<9:05:45,  5.60s/it]

Checkpoint saved: 1094813 unique posts
Progress: 4150/10000 queries completed | 1094813 unique posts saved

 42%|████▏     | 4174/10000 [8:46:05<4:50:25,  2.99s/it]

Checkpoint saved: 1098390 unique posts
Progress: 4175/10000 queries completed | 1098390 unique posts saved

 42%|████▏     | 4199/10000 [8:47:35<6:28:58,  4.02s/it]

Checkpoint saved: 1103519 unique posts
Progress: 4200/10000 queries completed | 1103519 unique posts saved

 42%|████▏     | 4224/10000 [8:48:55<7:10:57,  4.48s/it]

Checkpoint saved: 1107733 unique posts
Progress: 4225/10000 queries completed | 1107733 unique posts saved

 42%|████▏     | 4249/10000 [8:51:17<6:36:22,  4.14s/it]

Checkpoint saved: 1115134 unique posts
Progress: 4250/10000 queries completed | 1115134 unique posts saved
Long pause after 4250 queries...

 43%|████▎     | 4269/10000 [8:53:32<12:01:45,  7.56s/it]

Error query=$FRDM, page=2, attempt=1: Response(success=False, status_code=502, content=XrpcError(error='InternalServerError', message='Upstream server responded with a 500 error'), headers={'x-powered-by': 'Express', 'access-control-allow-origin': '*', 'ratelimit-limit': '3000', 'ratelimit-reset': '1782857950', 'ratelimit-remaining': '2945', 'ratelimit-policy': '3000;w=300', 'cache-control': 'private', 'vary': 'Authorization, Accept-Encoding', 'content-type': 'application/json; charset=utf-8', 'content-length': '86', 'etag': 'W/"56-L+jRpk9/y0j/QRmuMywPl8zmsSc"', 'date': 'Tue, 30 Jun 2026 22:15:49 GMT', 'keep-alive': 'timeout=90', 'strict-transport-security': 'max-age=63072000'})

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()

Error query=$FRDM, page=2, attempt=2: Response(success=False, status_code=502, content=XrpcError(error='InternalServerError', message='Upstream server responded with a 500 error'), headers={'x-powered-by': 'Express', 'access-control-allow-origin': '*', 'ratelimit-limit': '3000', 'ratelimit-reset': '1782857950', 'ratelimit-remaining': '2944', 'ratelimit-policy': '3000;w=300', 'cache-control': 'private', 'vary': 'Authorization, Accept-Encoding', 'content-type': 'application/json; charset=utf-8', 'content-length': '86', 'etag': 'W/"56-L+jRpk9/y0j/QRmuMywPl8zmsSc"', 'date': 'Tue, 30 Jun 2026 22:16:04 GMT', 'keep-alive': 'timeout=90', 'strict-transport-security': 'max-age=63072000'})

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 43%|████▎     | 4274/10000 [8:54:56<17:10:42, 10.80s/it]

Checkpoint saved: 1120665 unique posts
Progress: 4275/10000 queries completed | 1120665 unique posts saved

 43%|████▎     | 4299/10000 [8:56:56<5:08:41,  3.25s/it]

Checkpoint saved: 1126093 unique posts
Progress: 4300/10000 queries completed | 1126093 unique posts saved

 43%|████▎     | 4324/10000 [8:58:29<4:57:12,  3.14s/it]

Checkpoint saved: 1130981 unique posts
Progress: 4325/10000 queries completed | 1130981 unique posts saved

 43%|████▎     | 4349/10000 [8:59:58<4:01:30,  2.56s/it]

Checkpoint saved: 1136478 unique posts
Progress: 4350/10000 queries completed | 1136478 unique posts saved

 44%|████▎     | 4374/10000 [9:01:13<3:45:58,  2.41s/it]

Checkpoint saved: 1139313 unique posts
Progress: 4375/10000 queries completed | 1139313 unique posts saved

 44%|████▍     | 4399/10000 [9:02:30<5:36:27,  3.60s/it]

Checkpoint saved: 1143837 unique posts
Progress: 4400/10000 queries completed | 1143837 unique posts saved

 44%|████▍     | 4424/10000 [9:04:23<4:14:22,  2.74s/it]

Checkpoint saved: 1150049 unique posts
Progress: 4425/10000 queries completed | 1150049 unique posts saved

 44%|████▍     | 4449/10000 [9:06:12<6:46:59,  4.40s/it]

Checkpoint saved: 1156373 unique posts
Progress: 4450/10000 queries completed | 1156373 unique posts saved

 45%|████▍     | 4474/10000 [9:09:02<11:56:36,  7.78s/it]

Checkpoint saved: 1165546 unique posts
Progress: 4475/10000 queries completed | 1165546 unique posts saved

 45%|████▍     | 4486/10000 [9:10:11<7:30:20,  4.90s/it]

Error query=$GBCI, page=2, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 45%|████▍     | 4487/10000 [9:10:33<15:24:02, 10.06s/it]

Error query=$GBDC, page=1, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 45%|████▍     | 4488/10000 [9:10:52<19:15:15, 12.58s/it]

Error query=$GBF, page=2, attempt=1: Response(success=False, status_code=502, content=XrpcError(error='InternalServerError', message='Upstream server responded with a 500 error'), headers={'x-powered-by': 'Express', 'access-control-allow-origin': '*', 'ratelimit-limit': '3000', 'ratelimit-reset': '1782858854', 'ratelimit-remaining': '2881', 'ratelimit-policy': '3000;w=300', 'cache-control': 'private', 'vary': 'Authorization, Accept-Encoding', 'content-type': 'application/json; charset=utf-8', 'content-length': '86', 'etag': 'W/"56-L+jRpk9/y0j/QRmuMywPl8zmsSc"', 'date': 'Tue, 30 Jun 2026 22:33:09 GMT', 'keep-alive': 'timeout=90', 'strict-transport-security': 'max-age=63072000'})

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 45%|████▍     | 4499/10000 [9:11:53<7:31:10,  4.92s/it]

Checkpoint saved: 1171266 unique posts
Progress: 4500/10000 queries completed | 1171266 unique posts saved
Long pause after 4500 queries...

 45%|████▌     | 4524/10000 [9:14:08<6:15:15,  4.11s/it]

Checkpoint saved: 1176580 unique posts
Progress: 4525/10000 queries completed | 1176580 unique posts saved

 45%|████▌     | 4549/10000 [9:15:49<5:18:37,  3.51s/it]

Checkpoint saved: 1182601 unique posts
Progress: 4550/10000 queries completed | 1182601 unique posts saved

 46%|████▌     | 4574/10000 [9:17:58<8:38:10,  5.73s/it]

Checkpoint saved: 1190771 unique posts
Progress: 4575/10000 queries completed | 1190771 unique posts saved

 46%|████▌     | 4580/10000 [9:18:43<9:58:18,  6.62s/it]

Error query=$GEV, page=3, attempt=1: Response(success=False, status_code=502, content=XrpcError(error='UpstreamFailure', message='Upstream service unreachable'), headers={'x-powered-by': 'Express', 'access-control-allow-origin': '*', 'ratelimit-limit': '3000', 'ratelimit-reset': '1782859480', 'ratelimit-remaining': '2955', 'ratelimit-policy': '3000;w=300', 'cache-control': 'private', 'vary': 'Authorization, Accept-Encoding', 'content-type': 'application/json; charset=utf-8', 'content-length': '68', 'etag': 'W/"44-AJX0etNgxpDCFPcvTwgVOxfw5aw"', 'date': 'Tue, 30 Jun 2026 22:40:54 GMT', 'keep-alive': 'timeout=90', 'strict-transport-security': 'max-age=63072000'})

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 46%|████▌     | 4599/10000 [9:20:08<6:13:54,  4.15s/it]

Checkpoint saved: 1197949 unique posts
Progress: 4600/10000 queries completed | 1197949 unique posts saved

 46%|████▌     | 4624/10000 [9:21:49<3:57:06,  2.65s/it]

Checkpoint saved: 1203609 unique posts
Progress: 4625/10000 queries completed | 1203609 unique posts saved

 46%|████▋     | 4649/10000 [9:23:58<8:21:39,  5.62s/it]

Checkpoint saved: 1210692 unique posts
Progress: 4650/10000 queries completed | 1210692 unique posts saved

 47%|████▋     | 4674/10000 [9:25:49<7:02:55,  4.76s/it]

Checkpoint saved: 1216891 unique posts
Progress: 4675/10000 queries completed | 1216891 unique posts saved

 47%|████▋     | 4699/10000 [9:27:25<8:58:49,  6.10s/it]

Checkpoint saved: 1222784 unique posts
Progress: 4700/10000 queries completed | 1222784 unique posts saved

 47%|████▋     | 4724/10000 [9:29:09<5:27:08,  3.72s/it]

Checkpoint saved: 1228492 unique posts
Progress: 4725/10000 queries completed | 1228492 unique posts saved

 47%|████▋     | 4749/10000 [9:30:42<5:45:27,  3.95s/it]

Checkpoint saved: 1234608 unique posts
Progress: 4750/10000 queries completed | 1234608 unique posts saved
Long pause after 4750 queries...

 48%|████▊     | 4774/10000 [9:33:29<6:46:55,  4.67s/it]

Checkpoint saved: 1242856 unique posts
Progress: 4775/10000 queries completed | 1242856 unique posts saved

 48%|████▊     | 4799/10000 [9:35:27<6:32:50,  4.53s/it]

Checkpoint saved: 1249443 unique posts
Progress: 4800/10000 queries completed | 1249443 unique posts saved

 48%|████▊     | 4824/10000 [9:37:15<9:03:40,  6.30s/it]

Checkpoint saved: 1254991 unique posts
Progress: 4825/10000 queries completed | 1254991 unique posts saved

 48%|████▊     | 4833/10000 [9:38:05<10:53:53,  7.59s/it]

Error query=$GRFS, page=2, attempt=1: Response(success=False, status_code=502, content=XrpcError(error='InternalServerError', message='Upstream server responded with a 500 error'), headers={'x-powered-by': 'Express', 'access-control-allow-origin': '*', 'ratelimit-limit': '3000', 'ratelimit-reset': '1782860687', 'ratelimit-remaining': '2984', 'ratelimit-policy': '3000;w=300', 'cache-control': 'private', 'vary': 'Authorization, Accept-Encoding', 'content-type': 'application/json; charset=utf-8', 'content-length': '86', 'etag': 'W/"56-L+jRpk9/y0j/QRmuMywPl8zmsSc"', 'date': 'Tue, 30 Jun 2026 23:00:22 GMT', 'keep-alive': 'timeout=90', 'strict-transport-security': 'max-age=63072000'})

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 48%|████▊     | 4849/10000 [9:39:56<9:44:08,  6.80s/it]

Checkpoint saved: 1261868 unique posts
Progress: 4850/10000 queries completed | 1261868 unique posts saved

 49%|████▊     | 4874/10000 [9:42:07<4:36:36,  3.24s/it]

Checkpoint saved: 1266502 unique posts
Progress: 4875/10000 queries completed | 1266502 unique posts saved

 49%|████▉     | 4899/10000 [9:43:10<3:25:22,  2.42s/it]

Checkpoint saved: 1269896 unique posts
Progress: 4900/10000 queries completed | 1269896 unique posts saved

 49%|████▉     | 4924/10000 [9:44:31<4:23:29,  3.11s/it]

Checkpoint saved: 1273830 unique posts
Progress: 4925/10000 queries completed | 1273830 unique posts saved

 49%|████▉     | 4949/10000 [9:46:44<4:03:23,  2.89s/it]

Checkpoint saved: 1282109 unique posts
Progress: 4950/10000 queries completed | 1282109 unique posts saved

 50%|████▉     | 4974/10000 [9:48:29<10:58:04,  7.86s/it]

Checkpoint saved: 1287359 unique posts
Progress: 4975/10000 queries completed | 1287359 unique posts saved

 50%|████▉     | 4999/10000 [9:50:52<6:42:52,  4.83s/it]

Checkpoint saved: 1295865 unique posts
Progress: 5000/10000 queries completed | 1295865 unique posts saved
Long pause after 5000 queries...

 50%|█████     | 5024/10000 [9:52:42<2:47:18,  2.02s/it]

Checkpoint saved: 1299861 unique posts
Progress: 5025/10000 queries completed | 1299861 unique posts saved

 50%|█████     | 5042/10000 [9:53:39<2:53:51,  2.10s/it]

Error query=$HCWB, page=3, attempt=1: Response(success=False, status_code=502, content=XrpcError(error='UpstreamFailure', message='Upstream service unreachable'), headers={'x-powered-by': 'Express', 'access-control-allow-origin': '*', 'ratelimit-limit': '3000', 'ratelimit-reset': '1782861589', 'ratelimit-remaining': '2956', 'ratelimit-policy': '3000;w=300', 'cache-control': 'private', 'vary': 'Authorization, Accept-Encoding', 'content-type': 'application/json; charset=utf-8', 'content-length': '68', 'etag': 'W/"44-AJX0etNgxpDCFPcvTwgVOxfw5aw"', 'date': 'Tue, 30 Jun 2026 23:15:52 GMT', 'keep-alive': 'timeout=90', 'strict-transport-security': 'max-age=63072000'})

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 50%|█████     | 5049/10000 [9:54:21<6:38:06,  4.82s/it]

Checkpoint saved: 1303804 unique posts
Progress: 5050/10000 queries completed | 1303804 unique posts saved

 51%|█████     | 5059/10000 [9:55:09<11:10:47,  8.15s/it]

Error query=$HEAL, page=3, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 51%|█████     | 5074/10000 [9:57:01<7:51:47,  5.75s/it]

Checkpoint saved: 1311252 unique posts
Progress: 5075/10000 queries completed | 1311252 unique posts saved

 51%|█████     | 5099/10000 [9:58:38<2:40:06,  1.96s/it]

Checkpoint saved: 1315831 unique posts
Progress: 5100/10000 queries completed | 1315831 unique posts saved

 51%|█████     | 5124/10000 [10:00:50<8:41:14,  6.41s/it]

Checkpoint saved: 1323521 unique posts
Progress: 5125/10000 queries completed | 1323521 unique posts saved

 51%|█████▏    | 5149/10000 [10:02:54<6:31:27,  4.84s/it]

Checkpoint saved: 1330612 unique posts
Progress: 5150/10000 queries completed | 1330612 unique posts saved

 52%|█████▏    | 5174/10000 [10:04:50<7:40:11,  5.72s/it]

Checkpoint saved: 1337805 unique posts
Progress: 5175/10000 queries completed | 1337805 unique posts saved

 52%|█████▏    | 5199/10000 [10:07:02<6:34:06,  4.93s/it]

Checkpoint saved: 1345288 unique posts
Progress: 5200/10000 queries completed | 1345288 unique posts saved

 52%|█████▏    | 5211/10000 [10:08:08<8:39:15,  6.51s/it]

Error query=$HRB, page=3, attempt=1: Response(success=False, status_code=502, content=XrpcError(error='InternalServerError', message='Upstream server responded with a 500 error'), headers={'x-powered-by': 'Express', 'access-control-allow-origin': '*', 'ratelimit-limit': '3000', 'ratelimit-reset': '1782862491', 'ratelimit-remaining': '2983', 'ratelimit-policy': '3000;w=300', 'cache-control': 'private', 'vary': 'Authorization, Accept-Encoding', 'content-type': 'application/json; charset=utf-8', 'content-length': '86', 'etag': 'W/"56-L+jRpk9/y0j/QRmuMywPl8zmsSc"', 'date': 'Tue, 30 Jun 2026 23:30:26 GMT', 'keep-alive': 'timeout=90', 'strict-transport-security': 'max-age=63072000'})

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 52%|█████▏    | 5213/10000 [10:08:46<16:19:50, 12.28s/it]

Error query=$HRL, page=2, attempt=1: Response(success=False, status_code=502, content=XrpcError(error='UpstreamFailure', message='Upstream service unreachable'), headers={'x-powered-by': 'Express', 'access-control-allow-origin': '*', 'ratelimit-limit': '3000', 'ratelimit-reset': '1782862491', 'ratelimit-remaining': '2973', 'ratelimit-policy': '3000;w=300', 'cache-control': 'private', 'vary': 'Authorization, Accept-Encoding', 'content-type': 'application/json; charset=utf-8', 'content-length': '68', 'etag': 'W/"44-AJX0etNgxpDCFPcvTwgVOxfw5aw"', 'date': 'Tue, 30 Jun 2026 23:30:56 GMT', 'keep-alive': 'timeout=90', 'strict-transport-security': 'max-age=63072000'})

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 52%|█████▏    | 5224/10000 [10:09:47<5:16:02,  3.97s/it]

Checkpoint saved: 1351716 unique posts
Progress: 5225/10000 queries completed | 1351716 unique posts saved

 52%|█████▏    | 5249/10000 [10:11:18<3:17:45,  2.50s/it]

Checkpoint saved: 1356695 unique posts
Progress: 5250/10000 queries completed | 1356695 unique posts saved
Long pause after 5250 queries...

 53%|█████▎    | 5274/10000 [10:13:46<7:24:18,  5.64s/it]

Checkpoint saved: 1363427 unique posts
Progress: 5275/10000 queries completed | 1363427 unique posts saved

 53%|█████▎    | 5299/10000 [10:15:10<3:24:14,  2.61s/it]

Checkpoint saved: 1368235 unique posts
Progress: 5300/10000 queries completed | 1368235 unique posts saved

 53%|█████▎    | 5324/10000 [10:16:32<5:27:54,  4.21s/it]

Checkpoint saved: 1371841 unique posts
Progress: 5325/10000 queries completed | 1371841 unique posts saved

 53%|█████▎    | 5349/10000 [10:18:06<7:19:17,  5.67s/it]

Checkpoint saved: 1377256 unique posts
Progress: 5350/10000 queries completed | 1377256 unique posts saved

 54%|█████▎    | 5374/10000 [10:19:19<1:49:34,  1.42s/it]

Checkpoint saved: 1381091 unique posts
Progress: 5375/10000 queries completed | 1381091 unique posts saved

 54%|█████▍    | 5399/10000 [10:20:22<3:33:19,  2.78s/it]

Checkpoint saved: 1384067 unique posts
Progress: 5400/10000 queries completed | 1384067 unique posts saved

 54%|█████▍    | 5424/10000 [10:21:38<3:42:17,  2.91s/it]

Checkpoint saved: 1388639 unique posts
Progress: 5425/10000 queries completed | 1388639 unique posts saved

 54%|█████▍    | 5449/10000 [10:23:04<7:23:59,  5.85s/it]

Checkpoint saved: 1393127 unique posts
Progress: 5450/10000 queries completed | 1393127 unique posts saved

 55%|█████▍    | 5474/10000 [10:25:00<7:30:42,  5.97s/it]

Checkpoint saved: 1399577 unique posts
Progress: 5475/10000 queries completed | 1399577 unique posts saved

 55%|█████▍    | 5499/10000 [10:26:29<4:49:40,  3.86s/it]

Checkpoint saved: 1404553 unique posts
Progress: 5500/10000 queries completed | 1404553 unique posts saved
Long pause after 5500 queries...

 55%|█████▌    | 5524/10000 [10:28:22<2:47:03,  2.24s/it]

Checkpoint saved: 1408872 unique posts
Progress: 5525/10000 queries completed | 1408872 unique posts saved

 55%|█████▌    | 5549/10000 [10:30:10<3:02:41,  2.46s/it]

Checkpoint saved: 1415849 unique posts
Progress: 5550/10000 queries completed | 1415849 unique posts saved

 56%|█████▌    | 5574/10000 [10:32:14<6:59:11,  5.68s/it]

Checkpoint saved: 1423392 unique posts
Progress: 5575/10000 queries completed | 1423392 unique posts saved

 56%|█████▌    | 5599/10000 [10:33:51<3:39:05,  2.99s/it]

Checkpoint saved: 1429259 unique posts
Progress: 5600/10000 queries completed | 1429259 unique posts saved

 56%|█████▌    | 5624/10000 [10:35:25<5:13:42,  4.30s/it]

Checkpoint saved: 1434580 unique posts
Progress: 5625/10000 queries completed | 1434580 unique posts saved

 56%|█████▋    | 5649/10000 [10:36:35<2:06:57,  1.75s/it]

Checkpoint saved: 1438498 unique posts
Progress: 5650/10000 queries completed | 1438498 unique posts saved

 57%|█████▋    | 5674/10000 [10:38:53<5:28:24,  4.55s/it]

Checkpoint saved: 1447318 unique posts
Progress: 5675/10000 queries completed | 1447318 unique posts saved

 57%|█████▋    | 5699/10000 [10:40:49<5:02:24,  4.22s/it]

Checkpoint saved: 1454325 unique posts
Progress: 5700/10000 queries completed | 1454325 unique posts saved

 57%|█████▋    | 5724/10000 [10:43:10<4:01:28,  3.39s/it]

Checkpoint saved: 1462595 unique posts
Progress: 5725/10000 queries completed | 1462595 unique posts saved

 57%|█████▋    | 5749/10000 [10:44:44<5:11:27,  4.40s/it]

Checkpoint saved: 1467996 unique posts
Progress: 5750/10000 queries completed | 1467996 unique posts saved
Long pause after 5750 queries...

 58%|█████▊    | 5774/10000 [10:46:49<5:03:54,  4.31s/it]

Checkpoint saved: 1473856 unique posts
Progress: 5775/10000 queries completed | 1473856 unique posts saved

 58%|█████▊    | 5799/10000 [10:48:19<6:03:28,  5.19s/it]

Checkpoint saved: 1478664 unique posts
Progress: 5800/10000 queries completed | 1478664 unique posts saved

 58%|█████▊    | 5824/10000 [10:49:59<3:07:22,  2.69s/it]

Checkpoint saved: 1484199 unique posts
Progress: 5825/10000 queries completed | 1484199 unique posts saved

 58%|█████▊    | 5849/10000 [10:51:53<3:20:53,  2.90s/it]

Checkpoint saved: 1490259 unique posts
Progress: 5850/10000 queries completed | 1490259 unique posts saved

 59%|█████▊    | 5874/10000 [10:53:17<3:24:55,  2.98s/it]

Checkpoint saved: 1494773 unique posts
Progress: 5875/10000 queries completed | 1494773 unique posts saved

 59%|█████▉    | 5894/10000 [10:54:29<4:00:45,  3.52s/it]

Error query=$IVV, page=5, attempt=1: Response(success=False, status_code=502, content=XrpcError(error='UpstreamFailure', message='Upstream service unreachable'), headers={'x-powered-by': 'Express', 'access-control-allow-origin': '*', 'ratelimit-limit': '3000', 'ratelimit-reset': '1782865197', 'ratelimit-remaining': '2922', 'ratelimit-policy': '3000;w=300', 'cache-control': 'private', 'vary': 'Authorization, Accept-Encoding', 'content-type': 'application/json; charset=utf-8', 'content-length': '68', 'etag': 'W/"44-AJX0etNgxpDCFPcvTwgVOxfw5aw"', 'date': 'Wed, 01 Jul 2026 00:16:43 GMT', 'keep-alive': 'timeout=90', 'strict-transport-security': 'max-age=63072000'})

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 59%|█████▉    | 5899/10000 [10:54:54<3:27:00,  3.03s/it]

Checkpoint saved: 1499695 unique posts
Progress: 5900/10000 queries completed | 1499695 unique posts saved

 59%|█████▉    | 5924/10000 [10:57:03<6:29:47,  5.74s/it]

Checkpoint saved: 1507342 unique posts
Progress: 5925/10000 queries completed | 1507342 unique posts saved

 59%|█████▉    | 5949/10000 [10:59:04<6:02:49,  5.37s/it]

Checkpoint saved: 1515146 unique posts
Progress: 5950/10000 queries completed | 1515146 unique posts saved

 60%|█████▉    | 5974/10000 [11:01:15<5:14:38,  4.69s/it]

Checkpoint saved: 1523173 unique posts
Progress: 5975/10000 queries completed | 1523173 unique posts saved

 60%|█████▉    | 5999/10000 [11:02:51<2:45:41,  2.48s/it]

Checkpoint saved: 1528770 unique posts
Progress: 6000/10000 queries completed | 1528770 unique posts saved
Long pause after 6000 queries...

 60%|██████    | 6024/10000 [11:05:02<3:25:16,  3.10s/it]

Checkpoint saved: 1534214 unique posts
Progress: 6025/10000 queries completed | 1534214 unique posts saved

 60%|██████    | 6049/10000 [11:06:07<1:27:48,  1.33s/it]

Checkpoint saved: 1537318 unique posts
Progress: 6050/10000 queries completed | 1537318 unique posts saved

 61%|██████    | 6074/10000 [11:07:47<3:36:23,  3.31s/it]

Checkpoint saved: 1543457 unique posts
Progress: 6075/10000 queries completed | 1543457 unique posts saved

 61%|██████    | 6093/10000 [11:09:33<8:32:50,  7.88s/it]

Error query=$JOUT, page=3, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()

Error query=$JOUT, page=3, attempt=2: Response(success=False, status_code=502, content=XrpcError(error='InternalServerError', message='Upstream server responded with a 500 error'), headers={'x-powered-by': 'Express', 'access-control-allow-origin': '*', 'ratelimit-limit': '3000', 'ratelimit-reset': '1782866105', 'ratelimit-remaining': '2937', 'ratelimit-policy': '3000;w=300', 'cache-control': 'private', 'vary': 'Authorization, Accept-Encoding', 'content-type': 'application/json; charset=utf-8', 'content-length': '86', 'etag': 'W/"56-L+jRpk9/y0j/QRmuMywPl8zmsSc"', 'date': 'Wed, 01 Jul 2026 00:32:06 GMT', 'keep-alive': 'timeout=90', 'strict-transport-security': 'max-age=63072000'})

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()

Error query=$JOUT, page=3, attempt=3:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 61%|██████    | 6099/10000 [11:11:12<8:27:43,  7.81s/it]

Checkpoint saved: 1549075 unique posts
Progress: 6100/10000 queries completed | 1549075 unique posts saved

 61%|██████    | 6124/10000 [11:12:21<2:34:26,  2.39s/it]

Checkpoint saved: 1552928 unique posts
Progress: 6125/10000 queries completed | 1552928 unique posts saved

 61%|██████▏   | 6149/10000 [11:13:43<3:53:57,  3.65s/it]

Checkpoint saved: 1557776 unique posts
Progress: 6150/10000 queries completed | 1557776 unique posts saved

 62%|██████▏   | 6168/10000 [11:15:12<5:28:51,  5.15s/it]

Error query=$KALU, page=5, attempt=1: Response(success=False, status_code=502, content=XrpcError(error='UpstreamFailure', message='Upstream service unreachable'), headers={'x-powered-by': 'Express', 'access-control-allow-origin': '*', 'ratelimit-limit': '3000', 'ratelimit-reset': '1782866406', 'ratelimit-remaining': '2896', 'ratelimit-policy': '3000;w=300', 'cache-control': 'private', 'vary': 'Authorization, Accept-Encoding', 'content-type': 'application/json; charset=utf-8', 'content-length': '68', 'etag': 'W/"44-AJX0etNgxpDCFPcvTwgVOxfw5aw"', 'date': 'Wed, 01 Jul 2026 00:37:26 GMT', 'keep-alive': 'timeout=90', 'strict-transport-security': 'max-age=63072000'})

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 62%|██████▏   | 6174/10000 [11:15:59<6:45:43,  6.36s/it]

Checkpoint saved: 1565512 unique posts
Progress: 6175/10000 queries completed | 1565512 unique posts saved

 62%|██████▏   | 6199/10000 [11:17:24<3:25:53,  3.25s/it]

Checkpoint saved: 1570185 unique posts
Progress: 6200/10000 queries completed | 1570185 unique posts saved

 62%|██████▏   | 6224/10000 [11:18:54<3:41:03,  3.51s/it]

Checkpoint saved: 1575165 unique posts
Progress: 6225/10000 queries completed | 1575165 unique posts saved

 62%|██████▏   | 6249/10000 [11:20:25<3:07:39,  3.00s/it]

Checkpoint saved: 1580142 unique posts
Progress: 6250/10000 queries completed | 1580142 unique posts saved
Long pause after 6250 queries...

 63%|██████▎   | 6274/10000 [11:22:53<3:41:48,  3.57s/it]

Checkpoint saved: 1586907 unique posts
Progress: 6275/10000 queries completed | 1586907 unique posts saved

 63%|██████▎   | 6299/10000 [11:24:26<4:05:57,  3.99s/it]

Checkpoint saved: 1592949 unique posts
Progress: 6300/10000 queries completed | 1592949 unique posts saved

 63%|██████▎   | 6324/10000 [11:26:46<6:10:59,  6.06s/it]

Checkpoint saved: 1601659 unique posts
Progress: 6325/10000 queries completed | 1601659 unique posts saved

 63%|██████▎   | 6327/10000 [11:27:12<7:20:30,  7.20s/it]

Error query=$KOYN, page=1, attempt=1: Response(success=False, status_code=502, content=XrpcError(error='UpstreamFailure', message='Upstream service unreachable'), headers={'x-powered-by': 'Express', 'access-control-allow-origin': '*', 'ratelimit-limit': '3000', 'ratelimit-reset': '1782867010', 'ratelimit-remaining': '2812', 'ratelimit-policy': '3000;w=300', 'cache-control': 'private', 'vary': 'Authorization, Accept-Encoding', 'content-type': 'application/json; charset=utf-8', 'content-length': '68', 'etag': 'W/"44-AJX0etNgxpDCFPcvTwgVOxfw5aw"', 'date': 'Wed, 01 Jul 2026 00:49:23 GMT', 'keep-alive': 'timeout=90', 'strict-transport-security': 'max-age=63072000'})

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 63%|██████▎   | 6349/10000 [11:28:25<4:04:05,  4.01s/it]

Checkpoint saved: 1606238 unique posts
Progress: 6350/10000 queries completed | 1606238 unique posts saved

 64%|██████▎   | 6374/10000 [11:30:20<5:50:57,  5.81s/it]

Checkpoint saved: 1613394 unique posts
Progress: 6375/10000 queries completed | 1613394 unique posts saved

 64%|██████▍   | 6399/10000 [11:31:57<4:31:40,  4.53s/it]

Checkpoint saved: 1619065 unique posts
Progress: 6400/10000 queries completed | 1619065 unique posts saved

 64%|██████▍   | 6424/10000 [11:33:54<4:51:30,  4.89s/it]

Checkpoint saved: 1625705 unique posts
Progress: 6425/10000 queries completed | 1625705 unique posts saved

 64%|██████▍   | 6449/10000 [11:36:04<6:18:12,  6.39s/it]

Checkpoint saved: 1633936 unique posts
Progress: 6450/10000 queries completed | 1633936 unique posts saved

 65%|██████▍   | 6474/10000 [11:37:31<2:42:10,  2.76s/it]

Checkpoint saved: 1638355 unique posts
Progress: 6475/10000 queries completed | 1638355 unique posts saved

 65%|██████▍   | 6499/10000 [11:39:19<6:18:32,  6.49s/it]

Checkpoint saved: 1643535 unique posts
Progress: 6500/10000 queries completed | 1643535 unique posts saved
Long pause after 6500 queries...

 65%|██████▌   | 6524/10000 [11:42:16<2:02:22,  2.11s/it]

Checkpoint saved: 1651023 unique posts
Progress: 6525/10000 queries completed | 1651023 unique posts saved

 65%|██████▌   | 6549/10000 [11:43:28<3:33:04,  3.70s/it]

Checkpoint saved: 1654893 unique posts
Progress: 6550/10000 queries completed | 1654893 unique posts saved

 66%|██████▌   | 6574/10000 [11:45:42<6:51:44,  7.21s/it]

Checkpoint saved: 1662713 unique posts
Progress: 6575/10000 queries completed | 1662713 unique posts saved

 66%|██████▌   | 6599/10000 [11:48:12<6:42:12,  7.10s/it]

Checkpoint saved: 1671022 unique posts
Progress: 6600/10000 queries completed | 1671022 unique posts saved

 66%|██████▌   | 6624/10000 [11:49:28<3:26:33,  3.67s/it]

Checkpoint saved: 1674323 unique posts
Progress: 6625/10000 queries completed | 1674323 unique posts saved

 66%|██████▋   | 6649/10000 [11:51:26<5:12:34,  5.60s/it]

Checkpoint saved: 1681708 unique posts
Progress: 6650/10000 queries completed | 1681708 unique posts saved

 67%|██████▋   | 6674/10000 [11:53:48<2:12:41,  2.39s/it]

Checkpoint saved: 1688088 unique posts
Progress: 6675/10000 queries completed | 1688088 unique posts saved

 67%|██████▋   | 6698/10000 [11:55:08<2:39:05,  2.89s/it]

Error query=$LRE, page=5, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 67%|██████▋   | 6699/10000 [11:55:30<7:56:04,  8.65s/it]

Checkpoint saved: 1692065 unique posts
Progress: 6700/10000 queries completed | 1692065 unique posts saved

 67%|██████▋   | 6724/10000 [11:56:51<3:17:10,  3.61s/it]

Checkpoint saved: 1696684 unique posts
Progress: 6725/10000 queries completed | 1696684 unique posts saved

 67%|██████▋   | 6749/10000 [11:58:46<4:51:05,  5.37s/it]

Checkpoint saved: 1702560 unique posts
Progress: 6750/10000 queries completed | 1702560 unique posts saved
Long pause after 6750 queries...

 68%|██████▊   | 6774/10000 [12:00:41<2:40:46,  2.99s/it]

Checkpoint saved: 1707276 unique posts
Progress: 6775/10000 queries completed | 1707276 unique posts saved

 68%|██████▊   | 6799/10000 [12:03:03<5:14:35,  5.90s/it]

Checkpoint saved: 1715843 unique posts
Progress: 6800/10000 queries completed | 1715843 unique posts saved

 68%|██████▊   | 6824/10000 [12:05:40<4:41:53,  5.33s/it]

Checkpoint saved: 1725242 unique posts
Progress: 6825/10000 queries completed | 1725242 unique posts saved

 68%|██████▊   | 6849/10000 [12:08:09<4:47:40,  5.48s/it]

Checkpoint saved: 1733328 unique posts
Progress: 6850/10000 queries completed | 1733328 unique posts saved

 69%|██████▊   | 6874/10000 [12:09:44<3:42:41,  4.27s/it]

Checkpoint saved: 1738824 unique posts
Progress: 6875/10000 queries completed | 1738824 unique posts saved

 69%|██████▉   | 6899/10000 [12:11:11<2:58:09,  3.45s/it]

Checkpoint saved: 1743431 unique posts
Progress: 6900/10000 queries completed | 1743431 unique posts saved

 69%|██████▉   | 6924/10000 [12:12:59<3:23:27,  3.97s/it]

Checkpoint saved: 1749934 unique posts
Progress: 6925/10000 queries completed | 1749934 unique posts saved

 69%|██████▉   | 6949/10000 [12:14:35<3:48:53,  4.50s/it]

Checkpoint saved: 1755686 unique posts
Progress: 6950/10000 queries completed | 1755686 unique posts saved

 70%|██████▉   | 6974/10000 [12:17:04<3:10:12,  3.77s/it]

Checkpoint saved: 1764126 unique posts
Progress: 6975/10000 queries completed | 1764126 unique posts saved

 70%|██████▉   | 6999/10000 [12:18:44<3:14:32,  3.89s/it]

Checkpoint saved: 1769504 unique posts
Progress: 7000/10000 queries completed | 1769504 unique posts saved
Long pause after 7000 queries...

 70%|███████   | 7024/10000 [12:20:43<2:52:43,  3.48s/it]

Checkpoint saved: 1774523 unique posts
Progress: 7025/10000 queries completed | 1774523 unique posts saved

 70%|███████   | 7049/10000 [12:22:22<3:34:38,  4.36s/it]

Checkpoint saved: 1780524 unique posts
Progress: 7050/10000 queries completed | 1780524 unique posts saved

 71%|███████   | 7074/10000 [12:25:17<5:47:40,  7.13s/it]

Checkpoint saved: 1789971 unique posts
Progress: 7075/10000 queries completed | 1789971 unique posts saved

 71%|███████   | 7099/10000 [12:26:54<2:08:53,  2.67s/it]

Checkpoint saved: 1794759 unique posts
Progress: 7100/10000 queries completed | 1794759 unique posts saved

 71%|███████   | 7124/10000 [12:28:23<2:47:52,  3.50s/it]

Checkpoint saved: 1799481 unique posts
Progress: 7125/10000 queries completed | 1799481 unique posts saved

 71%|███████▏  | 7149/10000 [12:30:16<3:23:13,  4.28s/it]

Checkpoint saved: 1806235 unique posts
Progress: 7150/10000 queries completed | 1806235 unique posts saved

 72%|███████▏  | 7174/10000 [12:31:37<2:24:22,  3.07s/it]

Checkpoint saved: 1810317 unique posts
Progress: 7175/10000 queries completed | 1810317 unique posts saved

 72%|███████▏  | 7199/10000 [12:33:54<4:03:25,  5.21s/it]

Checkpoint saved: 1818664 unique posts
Progress: 7200/10000 queries completed | 1818664 unique posts saved

 72%|███████▏  | 7224/10000 [12:36:17<3:16:15,  4.24s/it]

Checkpoint saved: 1827195 unique posts
Progress: 7225/10000 queries completed | 1827195 unique posts saved

 72%|███████▏  | 7249/10000 [12:38:14<4:32:35,  5.95s/it]

Checkpoint saved: 1833925 unique posts
Progress: 7250/10000 queries completed | 1833925 unique posts saved
Long pause after 7250 queries...

 73%|███████▎  | 7274/10000 [12:40:41<3:26:43,  4.55s/it]

Checkpoint saved: 1840350 unique posts
Progress: 7275/10000 queries completed | 1840350 unique posts saved

 73%|███████▎  | 7299/10000 [12:42:28<1:54:50,  2.55s/it]

Checkpoint saved: 1846987 unique posts
Progress: 7300/10000 queries completed | 1846987 unique posts saved

 73%|███████▎  | 7324/10000 [12:44:21<2:58:07,  3.99s/it]

Checkpoint saved: 1853731 unique posts
Progress: 7325/10000 queries completed | 1853731 unique posts saved

 73%|███████▎  | 7349/10000 [12:46:26<4:02:00,  5.48s/it]

Checkpoint saved: 1861398 unique posts
Progress: 7350/10000 queries completed | 1861398 unique posts saved

 74%|███████▎  | 7374/10000 [12:48:29<2:02:08,  2.79s/it]

Checkpoint saved: 1867986 unique posts
Progress: 7375/10000 queries completed | 1867986 unique posts saved

 74%|███████▍  | 7399/10000 [12:50:12<1:12:02,  1.66s/it]

Checkpoint saved: 1874343 unique posts
Progress: 7400/10000 queries completed | 1874343 unique posts saved

 74%|███████▍  | 7424/10000 [12:51:39<2:13:26,  3.11s/it]

Checkpoint saved: 1879092 unique posts
Progress: 7425/10000 queries completed | 1879092 unique posts saved

 74%|███████▍  | 7449/10000 [12:53:46<3:42:22,  5.23s/it]

Checkpoint saved: 1886391 unique posts
Progress: 7450/10000 queries completed | 1886391 unique posts saved

 75%|███████▍  | 7474/10000 [12:55:55<1:31:33,  2.17s/it]

Checkpoint saved: 1893673 unique posts
Progress: 7475/10000 queries completed | 1893673 unique posts saved

 75%|███████▍  | 7499/10000 [12:57:15<2:24:00,  3.45s/it]

Checkpoint saved: 1897505 unique posts
Progress: 7500/10000 queries completed | 1897505 unique posts saved
Long pause after 7500 queries...

 75%|███████▌  | 7521/10000 [12:59:20<2:36:31,  3.79s/it]

Error query=$NDIA, page=2, attempt=1: Response(success=False, status_code=502, content=XrpcError(error='UpstreamFailure', message='Upstream service unreachable'), headers={'x-powered-by': 'Express', 'access-control-allow-origin': '*', 'ratelimit-limit': '3000', 'ratelimit-reset': '1782872773', 'ratelimit-remaining': '2985', 'ratelimit-policy': '3000;w=300', 'cache-control': 'private', 'vary': 'Authorization, Accept-Encoding', 'content-type': 'application/json; charset=utf-8', 'content-length': '68', 'etag': 'W/"44-AJX0etNgxpDCFPcvTwgVOxfw5aw"', 'date': 'Wed, 01 Jul 2026 02:21:32 GMT', 'keep-alive': 'timeout=90', 'strict-transport-security': 'max-age=63072000'})

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 75%|███████▌  | 7524/10000 [12:59:44<3:43:37,  5.42s/it]

Checkpoint saved: 1902878 unique posts
Progress: 7525/10000 queries completed | 1902878 unique posts saved

 75%|███████▌  | 7549/10000 [13:02:02<3:57:38,  5.82s/it]

Checkpoint saved: 1910751 unique posts
Progress: 7550/10000 queries completed | 1910751 unique posts saved

 76%|███████▌  | 7574/10000 [13:03:49<2:19:05,  3.44s/it]

Checkpoint saved: 1916456 unique posts
Progress: 7575/10000 queries completed | 1916456 unique posts saved

 76%|███████▌  | 7599/10000 [13:05:20<2:07:54,  3.20s/it]

Checkpoint saved: 1920833 unique posts
Progress: 7600/10000 queries completed | 1920833 unique posts saved

 76%|███████▌  | 7624/10000 [13:07:12<2:41:08,  4.07s/it]

Checkpoint saved: 1926833 unique posts
Progress: 7625/10000 queries completed | 1926833 unique posts saved

 76%|███████▋  | 7649/10000 [13:09:02<2:24:59,  3.70s/it]

Checkpoint saved: 1931872 unique posts
Progress: 7650/10000 queries completed | 1931872 unique posts saved

 77%|███████▋  | 7661/10000 [13:10:10<3:50:10,  5.90s/it]

Error query=$NMP, page=3, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 77%|███████▋  | 7674/10000 [13:11:30<2:31:44,  3.91s/it]

Checkpoint saved: 1938853 unique posts
Progress: 7675/10000 queries completed | 1938853 unique posts saved

 77%|███████▋  | 7699/10000 [13:13:37<3:07:42,  4.89s/it]

Checkpoint saved: 1946220 unique posts
Progress: 7700/10000 queries completed | 1946220 unique posts saved

 77%|███████▋  | 7724/10000 [13:15:17<3:12:46,  5.08s/it]

Checkpoint saved: 1950897 unique posts
Progress: 7725/10000 queries completed | 1950897 unique posts saved

 77%|███████▋  | 7749/10000 [13:16:43<2:26:27,  3.90s/it]

Checkpoint saved: 1955650 unique posts
Progress: 7750/10000 queries completed | 1955650 unique posts saved
Long pause after 7750 queries...

 78%|███████▊  | 7760/10000 [13:17:56<1:56:36,  3.12s/it]

Error query=$NTES, page=5, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 78%|███████▊  | 7774/10000 [13:19:05<2:22:47,  3.85s/it]

Checkpoint saved: 1960967 unique posts
Progress: 7775/10000 queries completed | 1960967 unique posts saved

 78%|███████▊  | 7799/10000 [13:20:24<2:30:58,  4.12s/it]

Checkpoint saved: 1964575 unique posts
Progress: 7800/10000 queries completed | 1964575 unique posts saved

 78%|███████▊  | 7824/10000 [13:21:46<2:29:06,  4.11s/it]

Checkpoint saved: 1969242 unique posts
Progress: 7825/10000 queries completed | 1969242 unique posts saved

 78%|███████▊  | 7849/10000 [13:23:03<1:29:33,  2.50s/it]

Checkpoint saved: 1972513 unique posts
Progress: 7850/10000 queries completed | 1972513 unique posts saved

 79%|███████▊  | 7873/10000 [13:24:35<2:11:25,  3.71s/it]

Error query=$NWL, page=5, attempt=1: Response(success=False, status_code=502, content=XrpcError(error='UpstreamFailure', message='Upstream service unreachable'), headers={'x-powered-by': 'Express', 'access-control-allow-origin': '*', 'ratelimit-limit': '3000', 'ratelimit-reset': '1782874285', 'ratelimit-remaining': '2980', 'ratelimit-policy': '3000;w=300', 'cache-control': 'private', 'vary': 'Authorization, Accept-Encoding', 'content-type': 'application/json; charset=utf-8', 'content-length': '68', 'etag': 'W/"44-AJX0etNgxpDCFPcvTwgVOxfw5aw"', 'date': 'Wed, 01 Jul 2026 02:46:49 GMT', 'keep-alive': 'timeout=90', 'strict-transport-security': 'max-age=63072000'})

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 79%|███████▊  | 7874/10000 [13:24:53<4:40:51,  7.93s/it]

Checkpoint saved: 1978210 unique posts
Progress: 7875/10000 queries completed | 1978210 unique posts saved

 79%|███████▉  | 7899/10000 [13:26:30<1:21:47,  2.34s/it]

Checkpoint saved: 1983167 unique posts
Progress: 7900/10000 queries completed | 1983167 unique posts saved

 79%|███████▉  | 7924/10000 [13:28:02<1:00:43,  1.76s/it]

Checkpoint saved: 1987677 unique posts
Progress: 7925/10000 queries completed | 1987677 unique posts saved

 79%|███████▉  | 7949/10000 [13:29:46<1:35:42,  2.80s/it]

Checkpoint saved: 1993704 unique posts
Progress: 7950/10000 queries completed | 1993704 unique posts saved

 80%|███████▉  | 7974/10000 [13:31:21<1:30:44,  2.69s/it]

Checkpoint saved: 1998733 unique posts
Progress: 7975/10000 queries completed | 1998733 unique posts saved

 80%|███████▉  | 7999/10000 [13:33:10<2:51:49,  5.15s/it]

Checkpoint saved: 2005435 unique posts
Progress: 8000/10000 queries completed | 2005435 unique posts saved
Long pause after 8000 queries...

 80%|████████  | 8024/10000 [13:35:10<1:47:15,  3.26s/it]

Checkpoint saved: 2010844 unique posts
Progress: 8025/10000 queries completed | 2010844 unique posts saved

 80%|████████  | 8049/10000 [13:37:31<3:48:25,  7.02s/it]

Checkpoint saved: 2019073 unique posts
Progress: 8050/10000 queries completed | 2019073 unique posts saved

 81%|████████  | 8074/10000 [13:39:25<2:34:41,  4.82s/it]

Checkpoint saved: 2025465 unique posts
Progress: 8075/10000 queries completed | 2025465 unique posts saved

 81%|████████  | 8099/10000 [13:41:12<1:38:34,  3.11s/it]

Checkpoint saved: 2030766 unique posts
Progress: 8100/10000 queries completed | 2030766 unique posts saved

 81%|████████  | 8124/10000 [13:43:17<2:23:14,  4.58s/it]

Checkpoint saved: 2037356 unique posts
Progress: 8125/10000 queries completed | 2037356 unique posts saved

 81%|████████▏ | 8149/10000 [13:45:06<1:52:20,  3.64s/it]

Checkpoint saved: 2044046 unique posts
Progress: 8150/10000 queries completed | 2044046 unique posts saved

 82%|████████▏ | 8174/10000 [13:46:47<1:52:03,  3.68s/it]

Checkpoint saved: 2048994 unique posts
Progress: 8175/10000 queries completed | 2048994 unique posts saved

 82%|████████▏ | 8199/10000 [13:48:56<57:14,  1.91s/it]

Checkpoint saved: 2055773 unique posts
Progress: 8200/10000 queries completed | 2055773 unique posts saved

 82%|████████▏ | 8224/10000 [13:50:30<2:16:52,  4.62s/it]

Checkpoint saved: 2060095 unique posts
Progress: 8225/10000 queries completed | 2060095 unique posts saved

 82%|████████▏ | 8249/10000 [13:52:50<2:49:26,  5.81s/it]

Checkpoint saved: 2069126 unique posts
Progress: 8250/10000 queries completed | 2069126 unique posts saved
Long pause after 8250 queries...

 83%|████████▎ | 8274/10000 [13:55:48<3:20:57,  6.99s/it]

Checkpoint saved: 2077336 unique posts
Progress: 8275/10000 queries completed | 2077336 unique posts saved

 83%|████████▎ | 8299/10000 [13:57:42<2:03:46,  4.37s/it]

Checkpoint saved: 2083544 unique posts
Progress: 8300/10000 queries completed | 2083544 unique posts saved

 83%|████████▎ | 8324/10000 [13:59:33<2:09:42,  4.64s/it]

Checkpoint saved: 2089595 unique posts
Progress: 8325/10000 queries completed | 2089595 unique posts saved

 83%|████████▎ | 8326/10000 [13:59:53<3:27:58,  7.45s/it]

Error query=$PCAP, page=1, attempt=1:

/var/folders/pw/y3ztzc9n5ns3pn2xk2j59d2w0000gp/T/ipykernel_7530/2195544028.py:53: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "timestamp": pd.Timestamp.utcnow().isoformat()
 83%|████████▎ | 8349/10000 [14:01:29<1:17:25,  2.81s/it]

Checkpoint saved: 2095655 unique posts
Progress: 8350/10000 queries completed | 2095655 unique posts saved

 84%|████████▎ | 8374/10000 [14:03:14<1:36:35,  3.56s/it]

Checkpoint saved: 2101691 unique posts
Progress: 8375/10000 queries completed | 2101691 unique posts saved

 84%|████████▍ | 8399/10000 [14:05:14<2:00:30,  4.52s/it]

Checkpoint saved: 2109076 unique posts
Progress: 8400/10000 queries completed | 2109076 unique posts saved

 84%|████████▍ | 8424/10000 [14:07:36<1:53:00,  4.30s/it]

Checkpoint saved: 2117290 unique posts
Progress: 8425/10000 queries completed | 2117290 unique posts saved

 84%|████████▍ | 8449/10000 [14:09:30<1:47:42,  4.17s/it]

Checkpoint saved: 2124549 unique posts
Progress: 8450/10000 queries completed | 2124549 unique posts saved

 85%|████████▍ | 8474/10000 [14:11:22<2:14:03,  5.27s/it]

Checkpoint saved: 2130830 unique posts
Progress: 8475/10000 queries completed | 2130830 unique posts saved

 85%|████████▍ | 8499/10000 [14:13:50<2:44:20,  6.57s/it]

Checkpoint saved: 2139296 unique posts
Progress: 8500/10000 queries completed | 2139296 unique posts saved
Long pause after 8500 queries...

 85%|████████▌ | 8524/10000 [14:16:22<1:17:16,  3.14s/it]

Checkpoint saved: 2146105 unique posts
Progress: 8525/10000 queries completed | 2146105 unique posts saved

 85%|████████▌ | 8549/10000 [14:18:17<55:20,  2.29s/it]

Checkpoint saved: 2152636 unique posts
Progress: 8550/10000 queries completed | 2152636 unique posts saved

 86%|████████▌ | 8574/10000 [14:20:09<2:43:37,  6.88s/it]

Checkpoint saved: 2159510 unique posts
Progress: 8575/10000 queries completed | 2159510 unique posts saved

 86%|████████▌ | 8599/10000 [14:21:44<1:12:49,  3.12s/it]

Checkpoint saved: 2164148 unique posts
Progress: 8600/10000 queries completed | 2164148 unique posts saved

 86%|████████▌ | 8624/10000 [14:23:19<1:35:11,  4.15s/it]

Checkpoint saved: 2169275 unique posts
Progress: 8625/10000 queries completed | 2169275 unique posts saved

 86%|████████▋ | 8649/10000 [14:26:04<2:54:46,  7.76s/it]

Checkpoint saved: 2178090 unique posts
Progress: 8650/10000 queries completed | 2178090 unique posts saved

 87%|████████▋ | 8674/10000 [14:27:54<44:34,  2.02s/it]

Checkpoint saved: 2184048 unique posts
Progress: 8675/10000 queries completed | 2184048 unique posts saved

 87%|████████▋ | 8699/10000 [14:29:52<1:38:14,  4.53s/it]

Checkpoint saved: 2190756 unique posts
Progress: 8700/10000 queries completed | 2190756 unique posts saved

 87%|████████▋ | 8724/10000 [14:31:50<1:16:21,  3.59s/it]

Checkpoint saved: 2198027 unique posts
Progress: 8725/10000 queries completed | 2198027 unique posts saved

 87%|████████▋ | 8749/10000 [14:33:28<56:18,  2.70s/it]

Checkpoint saved: 2203000 unique posts
Progress: 8750/10000 queries completed | 2203000 unique posts saved
Long pause after 8750 queries...

 88%|████████▊ | 8774/10000 [14:35:10<1:31:45,  4.49s/it]

Checkpoint saved: 2206874 unique posts
Progress: 8775/10000 queries completed | 2206874 unique posts saved

 88%|████████▊ | 8799/10000 [14:37:00<1:31:51,  4.59s/it]

Checkpoint saved: 2213336 unique posts
Progress: 8800/10000 queries completed | 2213336 unique posts saved

 88%|████████▊ | 8824/10000 [14:38:55<1:07:23,  3.44s/it]

Checkpoint saved: 2218852 unique posts
Progress: 8825/10000 queries completed | 2218852 unique posts saved

 88%|████████▊ | 8849/10000 [14:41:09<1:48:31,  5.66s/it]

Checkpoint saved: 2227474 unique posts
Progress: 8850/10000 queries completed | 2227474 unique posts saved

 89%|████████▊ | 8874/10000 [14:42:41<1:02:21,  3.32s/it]

Checkpoint saved: 2232064 unique posts
Progress: 8875/10000 queries completed | 2232064 unique posts saved

 89%|████████▉ | 8899/10000 [14:43:56<21:05,  1.15s/it]

Checkpoint saved: 2235687 unique posts
Progress: 8900/10000 queries completed | 2235687 unique posts saved

 89%|████████▉ | 8924/10000 [14:44:52<30:00,  1.67s/it]

Checkpoint saved: 2237129 unique posts
Progress: 8925/10000 queries completed | 2237129 unique posts saved

 89%|████████▉ | 8949/10000 [14:46:01<1:02:28,  3.57s/it]

Checkpoint saved: 2240354 unique posts
Progress: 8950/10000 queries completed | 2240354 unique posts saved

 90%|████████▉ | 8974/10000 [14:47:02<37:49,  2.21s/it]

Checkpoint saved: 2242841 unique posts
Progress: 8975/10000 queries completed | 2242841 unique posts saved

 90%|████████▉ | 8999/10000 [14:47:57<26:25,  1.58s/it]

Checkpoint saved: 2244964 unique posts
Progress: 9000/10000 queries completed | 2244964 unique posts saved
Long pause after 9000 queries...

 90%|█████████ | 9024/10000 [14:49:24<28:30,  1.75s/it]

Checkpoint saved: 2246810 unique posts
Progress: 9025/10000 queries completed | 2246810 unique posts saved

 90%|█████████ | 9049/10000 [14:50:46<52:37,  3.32s/it]

Checkpoint saved: 2251198 unique posts
Progress: 9050/10000 queries completed | 2251198 unique posts saved

 91%|█████████ | 9074/10000 [14:52:19<1:28:13,  5.72s/it]

Checkpoint saved: 2255680 unique posts
Progress: 9075/10000 queries completed | 2255680 unique posts saved

 91%|█████████ | 9099/10000 [14:54:57<1:32:22,  6.15s/it]

Checkpoint saved: 2263803 unique posts
Progress: 9100/10000 queries completed | 2263803 unique posts saved

 91%|█████████ | 9124/10000 [14:57:08<1:10:12,  4.81s/it]

Checkpoint saved: 2270544 unique posts
Progress: 9125/10000 queries completed | 2270544 unique posts saved

 91%|█████████▏| 9149/10000 [14:58:35<23:32,  1.66s/it]

Checkpoint saved: 2274831 unique posts
Progress: 9150/10000 queries completed | 2274831 unique posts saved

 92%|█████████▏| 9174/10000 [14:59:55<41:08,  2.99s/it]

Checkpoint saved: 2278779 unique posts
Progress: 9175/10000 queries completed | 2278779 unique posts saved

 92%|█████████▏| 9199/10000 [15:02:34<1:20:56,  6.06s/it]

Checkpoint saved: 2287986 unique posts
Progress: 9200/10000 queries completed | 2287986 unique posts saved

 92%|█████████▏| 9224/10000 [15:04:54<1:15:37,  5.85s/it]

Checkpoint saved: 2295633 unique posts
Progress: 9225/10000 queries completed | 2295633 unique posts saved

 92%|█████████▏| 9249/10000 [15:06:15<49:46,  3.98s/it]

Checkpoint saved: 2299633 unique posts
Progress: 9250/10000 queries completed | 2299633 unique posts saved
Long pause after 9250 queries...

 93%|█████████▎| 9274/10000 [15:08:37<1:00:19,  4.99s/it]

Checkpoint saved: 2304825 unique posts
Progress: 9275/10000 queries completed | 2304825 unique posts saved

 93%|█████████▎| 9299/10000 [15:10:34<56:11,  4.81s/it]

Checkpoint saved: 2311072 unique posts
Progress: 9300/10000 queries completed | 2311072 unique posts saved

 93%|█████████▎| 9324/10000 [15:11:59<48:42,  4.32s/it]

Checkpoint saved: 2314817 unique posts
Progress: 9325/10000 queries completed | 2314817 unique posts saved

 93%|█████████▎| 9349/10000 [15:13:23<22:10,  2.04s/it]

Checkpoint saved: 2319408 unique posts
Progress: 9350/10000 queries completed | 2319408 unique posts saved

 94%|█████████▎| 9374/10000 [15:14:58<49:00,  4.70s/it]

Checkpoint saved: 2324200 unique posts
Progress: 9375/10000 queries completed | 2324200 unique posts saved

 94%|█████████▍| 9399/10000 [15:17:30<1:04:03,  6.39s/it]

Checkpoint saved: 2333252 unique posts
Progress: 9400/10000 queries completed | 2333252 unique posts saved

 94%|█████████▍| 9424/10000 [15:19:30<37:54,  3.95s/it]

Checkpoint saved: 2339680 unique posts
Progress: 9425/10000 queries completed | 2339680 unique posts saved

 94%|█████████▍| 9449/10000 [15:20:42<24:56,  2.72s/it]

Checkpoint saved: 2343433 unique posts
Progress: 9450/10000 queries completed | 2343433 unique posts saved

 95%|█████████▍| 9474/10000 [15:22:16<47:55,  5.47s/it]

Checkpoint saved: 2348146 unique posts
Progress: 9475/10000 queries completed | 2348146 unique posts saved

 95%|█████████▍| 9499/10000 [15:23:57<19:51,  2.38s/it]

Checkpoint saved: 2353783 unique posts
Progress: 9500/10000 queries completed | 2353783 unique posts saved
Long pause after 9500 queries...

 95%|█████████▌| 9524/10000 [15:26:25<38:15,  4.82s/it]

Checkpoint saved: 2360419 unique posts
Progress: 9525/10000 queries completed | 2360419 unique posts saved

 95%|█████████▌| 9549/10000 [15:28:31<31:02,  4.13s/it]

Checkpoint saved: 2367574 unique posts
Progress: 9550/10000 queries completed | 2367574 unique posts saved

 96%|█████████▌| 9574/10000 [15:31:10<45:37,  6.43s/it]

Checkpoint saved: 2377109 unique posts
Progress: 9575/10000 queries completed | 2377109 unique posts saved

 96%|█████████▌| 9599/10000 [15:33:45<33:18,  4.98s/it]

Checkpoint saved: 2386097 unique posts
Progress: 9600/10000 queries completed | 2386097 unique posts saved

 96%|█████████▌| 9624/10000 [15:35:22<28:56,  4.62s/it]

Checkpoint saved: 2391342 unique posts
Progress: 9625/10000 queries completed | 2391342 unique posts saved

 96%|█████████▋| 9649/10000 [15:37:03<20:23,  3.49s/it]

Checkpoint saved: 2397277 unique posts
Progress: 9650/10000 queries completed | 2397277 unique posts saved

 97%|█████████▋| 9674/10000 [15:38:57<19:42,  3.63s/it]

Checkpoint saved: 2403700 unique posts
Progress: 9675/10000 queries completed | 2403700 unique posts saved

 97%|█████████▋| 9699/10000 [15:40:33<18:48,  3.75s/it]

Checkpoint saved: 2408886 unique posts
Progress: 9700/10000 queries completed | 2408886 unique posts saved

 97%|█████████▋| 9724/10000 [15:42:03<10:05,  2.19s/it]

Checkpoint saved: 2413554 unique posts
Progress: 9725/10000 queries completed | 2413554 unique posts saved

 97%|█████████▋| 9749/10000 [15:44:39<18:16,  4.37s/it]

Checkpoint saved: 2422591 unique posts
Progress: 9750/10000 queries completed | 2422591 unique posts saved
Long pause after 9750 queries...

 98%|█████████▊| 9774/10000 [15:47:39<20:43,  5.50s/it]

Checkpoint saved: 2430133 unique posts
Progress: 9775/10000 queries completed | 2430133 unique posts saved

 98%|█████████▊| 9799/10000 [15:49:28<16:22,  4.89s/it]

Checkpoint saved: 2435973 unique posts
Progress: 9800/10000 queries completed | 2435973 unique posts saved

 98%|█████████▊| 9824/10000 [15:51:09<13:46,  4.70s/it]

Checkpoint saved: 2441617 unique posts
Progress: 9825/10000 queries completed | 2441617 unique posts saved

 98%|█████████▊| 9849/10000 [15:53:14<05:47,  2.30s/it]

Checkpoint saved: 2448755 unique posts
Progress: 9850/10000 queries completed | 2448755 unique posts saved

 99%|█████████▊| 9874/10000 [15:55:33<10:08,  4.83s/it]

Checkpoint saved: 2456813 unique posts
Progress: 9875/10000 queries completed | 2456813 unique posts saved

 99%|█████████▉| 9899/10000 [15:57:52<05:48,  3.45s/it]

Checkpoint saved: 2464539 unique posts
Progress: 9900/10000 queries completed | 2464539 unique posts saved

 99%|█████████▉| 9924/10000 [16:00:01<05:40,  4.48s/it]

Checkpoint saved: 2471877 unique posts
Progress: 9925/10000 queries completed | 2471877 unique posts saved

 99%|█████████▉| 9949/10000 [16:01:58<02:34,  3.03s/it]

Checkpoint saved: 2478197 unique posts
Progress: 9950/10000 queries completed | 2478197 unique posts saved

100%|█████████▉| 9974/10000 [16:03:20<00:54,  2.11s/it]

Checkpoint saved: 2482768 unique posts
Progress: 9975/10000 queries completed | 2482768 unique posts saved

100%|█████████▉| 9999/10000 [16:04:53<00:01,  1.44s/it]

Checkpoint saved: 2487835 unique posts
Progress: 10000/10000 queries completed | 2487835 unique posts saved
Long pause after 10000 queries...

100%|██████████| 10000/10000 [16:05:42<00:00,  5.79s/it]

Checkpoint saved: 2487835 unique posts
DONE.
Completed queries: 10000
Large unique posts: 2487835
Saved posts checkpoint to: /Users/bucco/Downloads/outputs/bluesky_large_10000_seeded_posts_checkpoint.csv
Saved completed queries to: /Users/bucco/Downloads/outputs/bluesky_large_10000_completed_queries.txt

,query,uri,cid,author_handle,author_did,created_at,text,like_count,reply_count,repost_count,quote_count
0,$SPY,at://did:plc:7vcmsr34a4fmn33syokw62ir/app.bsky...,bafyreihetpfrvpdurm7k7kpd66vmpbg43iwkm3dzrqxy2...,ericcalkins.bsky.social,did:plc:7vcmsr34a4fmn33syokw62ir,2026-06-30T13:20:54.807Z,Related: suppose one had the choice of three I...,0,0,0,0
1,$SPY,at://did:plc:z6rujpf4u56jfie7aqic2nfg/app.bsky...,bafyreiffxx2fpkigk7xrfb3thwk62vdd7ctltviivxg2p...,carlquintanilla.bsky.social,did:plc:z6rujpf4u56jfie7aqic2nfg,2026-06-30T13:20:48.581Z,"OPCO DESK: "".. For only second time since 2010...",5,0,1,0
2,$SPY,at://did:plc:kmc3trloj2jezhby2k2nadkr/app.bsky...,bafyreigrenhoxlc2wf2d7dhuvttfjpvthxps5z55vm2n3...,magnoliara.bsky.social,did:plc:kmc3trloj2jezhby2k2nadkr,2026-06-30T13:20:42.688Z,KSE: btw im a spy who infiltrated the gov\nBro...,0,0,0,0
3,$SPY,at://did:plc:47ukz5svch7g2jmqu674y7b5/app.bsky...,bafyreicfkg2ftkwhzeooglrqh3ppxqiswflk55oqaacmn...,eu-gb.bsky.social,did:plc:47ukz5svch7g2jmqu674y7b5,2026-06-30T13:15:15+00:00,Nuclear weapons storage in spotlight as US pla...,0,0,0,0
4,$SPY,at://did:plc:nnfjy7mgugylrbiasa7pqidb/app.bsky...,bafyreibgfnkxwmfxscf3av65optvyvxjrczhcyce7oqwz...,notimeforwaifus.bsky.social,did:plc:nnfjy7mgugylrbiasa7pqidb,2026-06-30T13:15:08.449Z,"Yor, your beauty and elegance are completely i...",3,0,0,0
5,$SPY,at://did:plc:mbt5u6e4b77dgihfhvlvpkxt/app.bsky...,bafyreigb6qk5a4lgy6noetsksfamfs3xpm2wos5hvy6by...,teawhalem.bsky.social,did:plc:mbt5u6e4b77dgihfhvlvpkxt,2026-06-30T13:15:03.883Z,The Last Act of an Unusual Spy Chief\nopen.sub...,0,0,0,1
6,$SPY,at://did:plc:k6orgxkypgzp3dmkzyu37qzk/app.bsky...,bafyreieqcvoytwsaxywyqsg3bfmfv5pklr27mvbqw4ijh...,numbcat9.bsky.social,did:plc:k6orgxkypgzp3dmkzyu37qzk,2026-06-30T13:13:32.674Z,He literally let the head of Russia’s spy agen...,0,0,1,0
7,$SPY,at://did:plc:bfrqponecue5czek3awk6ydd/app.bsky...,bafyreid2plus4xavabal245rs7mr254wlscn7lfids3bq...,pixelwelten.eurosky.social,did:plc:bfrqponecue5czek3awk6ydd,2026-06-30T13:06:58.301Z,"Pokemon Go kloppen, aber mit Rayban und Meta C...",1,0,0,0
8,$SPY,at://did:plc:nnfjy7mgugylrbiasa7pqidb/app.bsky...,bafyreiefsq3fk3eip3qn42puf2djituetb6arcscnn74v...,notimeforwaifus.bsky.social,did:plc:nnfjy7mgugylrbiasa7pqidb,2026-06-30T13:02:58.952Z,"The most intimate, mouth-watering view of Yor....",7,0,0,0
9,$SPY,at://did:plc:q2bofj35scvkbetpou2ulrt4/app.bsky...,bafyreia2vnc7pse2l6b3grlyqzt6vhbrpy2uinl52up3z...,jacobschneider.bsky.social,did:plc:q2bofj35scvkbetpou2ulrt4,2026-06-30T13:02:35.993Z,I spy something perfect,1,0,1,0

In [21]:
# ============================================================
# MERGE ORIGINAL FINANCE-QUERY RUN WITH LARGE TICKER-SEEDED RUN
# ============================================================

large_posts_df = pd.read_csv(LARGE_POSTS_CHECKPOINT_PATH)

combined_posts_df = pd.concat(
    [posts_df, large_posts_df],
    ignore_index=True
)

combined_posts_df = combined_posts_df.drop_duplicates(subset=["uri"]).reset_index(drop=True)

combined_posts_path = OUTPUT_DIR / "bluesky_posts_combined_10000_seeded.csv"
combined_posts_df.to_csv(combined_posts_path, index=False)

print("Original finance-query posts:", len(posts_df))
print("Large ticker-seeded posts:", len(large_posts_df))
print("Combined unique posts:", len(combined_posts_df))
print("Saved combined posts to:", combined_posts_path)

display(combined_posts_df.head(10))

Original finance-query posts: 24766
Large ticker-seeded posts: 2487835
Combined unique posts: 2498033
Saved combined posts to: /Users/bucco/Downloads/outputs/bluesky_posts_combined_10000_seeded.csv

,query,uri,cid,author_handle,author_did,created_at,text,like_count,reply_count,repost_count,quote_count,tickers,num_tickers
0,stocks,at://did:plc:ilqsyryppoq2vgipjp3fnxiw/app.bsky...,bafyreigmwt4idfs3nwiwli7pqe2jsanec42tlounnfnro...,secwatch.bsky.social,did:plc:ilqsyryppoq2vgipjp3fnxiw,2026-06-30T13:07:23.556665Z,🚨 JUST IN: $HCWB\nHCW Biologics regains Nasdaq...,0,0,0,0,[HCWB],1.0
1,stocks,at://did:plc:ilqsyryppoq2vgipjp3fnxiw/app.bsky...,bafyreifuu6gsuuxl23yacycktrrgs7m5ban2q7b7cnnot...,secwatch.bsky.social,did:plc:ilqsyryppoq2vgipjp3fnxiw,2026-06-30T13:07:22.402435Z,🚨 JUST IN: $QXO\nQXO reports 99.5%+ tender of ...,0,0,0,0,[QXO],1.0
2,stocks,at://did:plc:gtw57nuw4wt2tqs322knhgim/app.bsky...,bafyreib3paf5vp3ojkgoauwnd73xw2juzqr5mmrdtqvk4...,capitalwisdom.bsky.social,did:plc:gtw57nuw4wt2tqs322knhgim,2026-06-30T13:07:15.980401+00:00,"📈 Capital Wisdom Top Picks — Jun 30, 2026\n\n$...",0,0,0,0,[PEP],1.0
3,stocks,at://did:plc:xhrtfphu4gzqrztkpb3a63qf/app.bsky...,bafyreif355gfx3gqcp6pbyzngywx422y7esnflrfxg6ma...,babygoldie.bsky.social,did:plc:xhrtfphu4gzqrztkpb3a63qf,2026-06-30T13:06:15.262304+00:00,"[3/4] in the future. After verification, the c...",0,1,0,0,[],0.0
4,stocks,at://did:plc:xhrtfphu4gzqrztkpb3a63qf/app.bsky...,bafyreic6sbrvrz47nmpzdktcj36ccjnsdkogpagewbwxk...,babygoldie.bsky.social,did:plc:xhrtfphu4gzqrztkpb3a63qf,2026-06-30T13:05:57.076841+00:00,[3/4] interest rates appear to be overdone. Th...,0,1,0,0,[],0.0
5,stocks,at://did:plc:xhrtfphu4gzqrztkpb3a63qf/app.bsky...,bafyreie3iucy2lea4s5gm37cyuv4qmxkqk7wgeufpngoc...,babygoldie.bsky.social,did:plc:xhrtfphu4gzqrztkpb3a63qf,2026-06-30T13:05:55.738359+00:00,[1/4] 2026-06-30 19:53:22 - [BlackRock downgra...,0,1,0,0,[],0.0
6,stocks,at://did:plc:xhrtfphu4gzqrztkpb3a63qf/app.bsky...,bafyreiayhvaj2ok6d6dzi5ui3kiq4mtdku75yc2izt5hg...,babygoldie.bsky.social,did:plc:xhrtfphu4gzqrztkpb3a63qf,2026-06-30T13:04:29.172633+00:00,"[3/5] characteristics of ""high scores clusteri...",0,1,0,0,[],0.0
7,stocks,at://did:plc:xhrtfphu4gzqrztkpb3a63qf/app.bsky...,bafyreif55gq3ffvddb4saydqfgtdu5ot37ax6hvs4ljfg...,babygoldie.bsky.social,did:plc:xhrtfphu4gzqrztkpb3a63qf,2026-06-30T13:03:50.262565+00:00,"[3/5] characteristics of ""high scores clusteri...",0,1,0,0,[],0.0
8,stocks,at://did:plc:2mmdgkpha4xuzppdqixd7q6g/app.bsky...,bafyreicmfmna74qb4y7l2dgyyrkh7b2hyvtw7qmgozpma...,aistorynews.bsky.social,did:plc:2mmdgkpha4xuzppdqixd7q6g,2026-06-30T13:03:32Z,"AI chipmaker rally lifts Asia markets, stokes ...",0,0,0,0,[],0.0
9,stocks,at://did:plc:brxtbyqsirrv66f3nqqgkvjz/app.bsky...,bafyreib5lpffxshauieg6vwv6wcyay2dpx5qqumh3ekqi...,chelseafinancial.bsky.social,did:plc:brxtbyqsirrv66f3nqqgkvjz,2026-06-30T06:03:27-07:00,#TechStocks #Stocks #USEconomy #2026Economy #I...,0,0,0,0,[],0.0

In [22]:
# ============================================================
# EXTRACT VALID TICKERS FROM LARGE COMBINED DATASET
# ============================================================

combined_posts_df["tickers"] = combined_posts_df["text"].apply(extract_valid_cashtag_tickers)
combined_posts_df["num_tickers"] = combined_posts_df["tickers"].apply(len)

combined_posts_with_1plus_ticker_df = combined_posts_df[
    combined_posts_df["num_tickers"] >= 1
].copy().reset_index(drop=True)

combined_ticker_posts_df = combined_posts_df[
    combined_posts_df["num_tickers"] >= 2
].copy().reset_index(drop=True)

unique_observed_tickers = sorted({
    ticker
    for tickers in combined_posts_df["tickers"]
    for ticker in tickers
})

print("Combined posts:", len(combined_posts_df))
print("Posts with at least 1 valid ticker:", len(combined_posts_with_1plus_ticker_df))
print("Posts with at least 2 valid tickers:", len(combined_ticker_posts_df))
print("Unique observed valid tickers:", len(unique_observed_tickers))

combined_posts_with_1plus_ticker_path = OUTPUT_DIR / "bluesky_posts_combined_10000_with_1plus_ticker.csv"
combined_ticker_posts_path = OUTPUT_DIR / "bluesky_posts_combined_10000_with_2plus_tickers.csv"
observed_tickers_path = OUTPUT_DIR / "bluesky_observed_valid_tickers_10000.txt"

combined_posts_with_1plus_ticker_df.to_csv(combined_posts_with_1plus_ticker_path, index=False)
combined_ticker_posts_df.to_csv(combined_ticker_posts_path, index=False)

with open(observed_tickers_path, "w") as f:
    for ticker in unique_observed_tickers:
        f.write(ticker + "\n")

print("Saved 1+ ticker posts to:", combined_posts_with_1plus_ticker_path)
print("Saved 2+ ticker posts to:", combined_ticker_posts_path)
print("Saved observed tickers to:", observed_tickers_path)

display(
    combined_ticker_posts_df[
        ["created_at", "author_handle", "text", "tickers", "num_tickers"]
    ].head(20)
)

Combined posts: 2498033
Posts with at least 1 valid ticker: 116461
Posts with at least 2 valid tickers: 25229
Unique observed valid tickers: 7642
Saved 1+ ticker posts to: /Users/bucco/Downloads/outputs/bluesky_posts_combined_10000_with_1plus_ticker.csv
Saved 2+ ticker posts to: /Users/bucco/Downloads/outputs/bluesky_posts_combined_10000_with_2plus_tickers.csv
Saved observed tickers to: /Users/bucco/Downloads/outputs/bluesky_observed_valid_tickers_10000.txt

,created_at,author_handle,text,tickers,num_tickers
0,2026-06-30T12:55:33.892Z,chrisversace.bsky.social,Apple’s New iPhone Leaks: 8 Key Items Shaping ...,"[AAPL, NKE, NVDA, PLTR, STZ]",5
1,2026-06-30T12:14:21.366Z,bestsidehustle.bsky.social,"Did you watch $BTC, $ETH, $AAPL, $AMZN repeat ...","[AAPL, AMZN, BTC, ETH]",4
2,2026-06-30T12:01:38.214Z,coingapenews.bsky.social,📈 Ark Invest Doubles Down on Crypto Stocks\n\n...,"[BLSH, COIN, CRCL, HOOD]",4
3,2026-06-30T11:01:02.992Z,iamjaredkim.bsky.social,Citi says 80% of Nasdaq longs are losing. That...,"[IWM, USO]",2
4,2026-06-29T18:37:25.000Z,mikezaccardi.bsky.social,Four Big Questions Facing the Stock Market in ...,"[IWM, MAGS, QQQ, SPY]",4
5,2026-06-30T12:53:14.766Z,coingapenews.bsky.social,📉 #MiCA Deadline Tomorrow\n\nMarkets are watch...,"[BTC, ETH, XRP]",3
6,2026-06-30T10:57:43.932Z,tokenaxishq.bsky.social,"Good morning, traders. 📈\nFinal trading day of...","[AMZN, NKE, STZ]",3
7,2026-06-30T03:36:10.330Z,wallstgamenotes.bsky.social,Can Nike Capitalize On Sports Mania? Q4 Earnin...,"[LULU, NKE]",2
8,2026-06-24T13:09:46.000Z,mikezaccardi.bsky.social,Banks $KBE lit heading into mid-year... and ea...,"[JPM, KBE]",2
9,2026-06-07T11:10:01.564518+00:00,kapualabs.bsky.social,When does a beat become a disappointment? This...,"[AMZN, GOOGL]",2
10,2026-06-01T00:08:40.952Z,stockexpertai.bsky.social,"Retail showing life, but $XRT still lagging th...","[SPY, XRT]",2
11,2026-05-29T10:07:21.327Z,sharesifysocial.bsky.social,Delivered one of the strongest quarterly repor...,"[DELL, NVDA]",2
12,2026-05-28T08:20:15.014Z,mindmathmoney.com,Earnings season is just the market re-pricing ...,"[MRVL, SNOW]",2
13,2026-05-20T12:48:06.644Z,robot2trade.bsky.social,Pre-Market Mayhem Returns!\nGainers: $SLXN +1...,"[GCL, IPW, JUNS, RUBI, SLXN]",5
14,2026-05-18T21:52:59.330Z,robot2trade.bsky.social,"After-Hours Madness! $AMST +87%, $AGYS +14.2%...","[AGYS, AMST, FATN, UBXG]",4
15,2026-05-14T12:10:22.352Z,robot2trade.bsky.social,Pre-market chaos! Top Gainers:\n$SNAL +198.7...,"[AEHL, ALP, DXF, MDXH, SNAL, STAK, WOK, YOOV]",8
16,2026-05-13T13:39:42.577Z,tiernanray.bsky.social,This week and last week tend to be the busiest...,"[DT, NBIS, NXT, TSEM]",4
17,2026-05-11T02:10:01.208Z,equityclock.bsky.social,The loss of earnings season distraction could ...,"[QQQ, SMH, SPY]",3
18,2026-05-07T21:46:46.051Z,robot2trade.bsky.social,Wild after-hours action! Top Gainers:\n$AIIO...,"[AIIO, AKAM, FWRD, HUBS, INOD, KDK]",6
19,2026-05-06T21:21:40.720Z,robot2trade.bsky.social,"AFTER-HOURS MAY 6: $GLE +57%, $OSG +42%, $FLN...","[ADMA, FLNC, FSLY, FTNT, GLE, ONEG, OSG]",7

In [23]:
# ============================================================
# BUILD LARGE TICKER CO-MENTION GRAPH
# ============================================================

from itertools import combinations
from collections import Counter
import pandas as pd
import networkx as nx

large_edge_counter = Counter()

for tickers in combined_ticker_posts_df["tickers"]:
    unique_tickers = sorted(set(tickers))

    if len(unique_tickers) >= 2:
        for source, target in combinations(unique_tickers, 2):
            large_edge_counter[(source, target)] += 1

large_edges_weighted_df = pd.DataFrame(
    [
        {
            "source": source,
            "target": target,
            "weight": weight
        }
        for (source, target), weight in large_edge_counter.items()
    ]
)

large_edges_weighted_df = large_edges_weighted_df.sort_values(
    ["weight", "source", "target"],
    ascending=[False, True, True]
).reset_index(drop=True)

large_edges_unweighted_df = large_edges_weighted_df[["source", "target"]].copy()
large_edges_unweighted_df["weight"] = 1

G_large_weighted = nx.Graph()

for _, row in large_edges_weighted_df.iterrows():
    G_large_weighted.add_edge(
        row["source"],
        row["target"],
        weight=int(row["weight"])
    )

G_large_unweighted = nx.Graph()

for _, row in large_edges_unweighted_df.iterrows():
    G_large_unweighted.add_edge(
        row["source"],
        row["target"],
        weight=1
    )

print("Large weighted graph")
print("Nodes:", G_large_weighted.number_of_nodes())
print("Edges:", G_large_weighted.number_of_edges())

print("\nLarge unweighted graph")
print("Nodes:", G_large_unweighted.number_of_nodes())
print("Edges:", G_large_unweighted.number_of_edges())

display(large_edges_weighted_df.head(30))

Large weighted graph
Nodes: 6243
Edges: 462904

Large unweighted graph
Nodes: 6243
Edges: 462904

   source target  weight
0     QQQ    SPY    2824
1     DIA    SPY    2053
2     DIA    QQQ    2052
3     BTC    ETH     912
4    NVDA   TSLA     655
5    NVDA    SPY     579
6    AAPL   NVDA     518
7     SPY   TSLA     517
8    AAPL   TSLA     497
9    NVDA    QQQ     487
10   AMZN  GOOGL     474
11   AAPL   AMZN     471
12    QQQ   TSLA     442
13    FXI   KWEB     439
14   ASHR   KWEB     436
15   ASHR    FXI     435
16    FXI   YINN     432
17   KWEB   YINN     431
18   ASHR   YINN     430
19    FXI   YANG     430
20   KWEB   YANG     430
21   YANG   YINN     430
22   ASHR   YANG     429
23   AAPL  GOOGL     426
24    BTC    XRP     418
25    ETH    XRP     417
26   AAPL    SPY     415
27   AMZN   META     415
28   AMZN   NVDA     410
29    LTC    XRP     410

In [24]:
# ============================================================
# SAVE LARGE GRAPH OUTPUTS FOR REPORT AND GEPHI
# ============================================================

if G_large_unweighted.number_of_nodes() > 0:
    connected_components = list(nx.connected_components(G_large_unweighted))
    largest_component = max(connected_components, key=len)
else:
    connected_components = []
    largest_component = set()

large_basic_stats = {
    "num_posts_combined": len(combined_posts_df),
    "num_posts_with_at_least_1_valid_ticker": len(combined_posts_with_1plus_ticker_df),
    "num_posts_with_at_least_2_valid_tickers": len(combined_ticker_posts_df),
    "unique_observed_valid_tickers": len(unique_observed_tickers),
    "num_nodes": G_large_unweighted.number_of_nodes(),
    "num_edges": G_large_unweighted.number_of_edges(),
    "density": nx.density(G_large_unweighted),
    "num_connected_components": nx.number_connected_components(G_large_unweighted),
    "largest_component_size": len(largest_component),
    "largest_component_share": (
        len(largest_component) / G_large_unweighted.number_of_nodes()
        if G_large_unweighted.number_of_nodes() > 0 else 0
    ),
    "average_degree": (
        sum(dict(G_large_unweighted.degree()).values()) / G_large_unweighted.number_of_nodes()
        if G_large_unweighted.number_of_nodes() > 0 else 0
    )
}

large_basic_stats_df = pd.DataFrame([large_basic_stats])

display(large_basic_stats_df)

# Save tables
large_edges_weighted_path = OUTPUT_DIR / "bluesky_large_edges_weighted_10000.csv"
large_edges_unweighted_path = OUTPUT_DIR / "bluesky_large_edges_unweighted_10000.csv"
large_basic_stats_path = OUTPUT_DIR / "bluesky_large_basic_stats_10000.csv"

large_edges_weighted_df.to_csv(large_edges_weighted_path, index=False)
large_edges_unweighted_df.to_csv(large_edges_unweighted_path, index=False)
large_basic_stats_df.to_csv(large_basic_stats_path, index=False)

# Save graph files
large_graphml_unweighted_path = OUTPUT_DIR / "bluesky_large_network_unweighted_10000.graphml"
large_gexf_unweighted_path = OUTPUT_DIR / "bluesky_large_network_unweighted_10000.gexf"
large_graphml_weighted_path = OUTPUT_DIR / "bluesky_large_network_weighted_10000.graphml"
large_gexf_weighted_path = OUTPUT_DIR / "bluesky_large_network_weighted_10000.gexf"

nx.write_graphml(G_large_unweighted, large_graphml_unweighted_path)
nx.write_gexf(G_large_unweighted, large_gexf_unweighted_path)

nx.write_graphml(G_large_weighted, large_graphml_weighted_path)
nx.write_gexf(G_large_weighted, large_gexf_weighted_path)

print("Saved weighted edges to:", large_edges_weighted_path)
print("Saved unweighted edges to:", large_edges_unweighted_path)
print("Saved stats to:", large_basic_stats_path)
print("Saved unweighted GraphML to:", large_graphml_unweighted_path)
print("Saved unweighted GEXF to:", large_gexf_unweighted_path)
print("Saved weighted GraphML to:", large_graphml_weighted_path)
print("Saved weighted GEXF to:", large_gexf_weighted_path)

,num_posts_combined,num_posts_with_at_least_1_valid_ticker,num_posts_with_at_least_2_valid_tickers,unique_observed_valid_tickers,num_nodes,num_edges,density,num_connected_components,largest_component_size,largest_component_share,average_degree
0,2498033,116461,25229,7642,6243,462904,0.023758,16,6211,0.994874,148.295371

Saved weighted edges to: /Users/bucco/Downloads/outputs/bluesky_large_edges_weighted_10000.csv
Saved unweighted edges to: /Users/bucco/Downloads/outputs/bluesky_large_edges_unweighted_10000.csv
Saved stats to: /Users/bucco/Downloads/outputs/bluesky_large_basic_stats_10000.csv
Saved unweighted GraphML to: /Users/bucco/Downloads/outputs/bluesky_large_network_unweighted_10000.graphml
Saved unweighted GEXF to: /Users/bucco/Downloads/outputs/bluesky_large_network_unweighted_10000.gexf
Saved weighted GraphML to: /Users/bucco/Downloads/outputs/bluesky_large_network_weighted_10000.graphml
Saved weighted GEXF to: /Users/bucco/Downloads/outputs/bluesky_large_network_weighted_10000.gexf